### PR TITLE
[Security] Update dependencies to the latest stable

### PR DESCRIPTION
**Pull request by L1ghtn1ng**
This updates all dependencies to the latest stable to fix multiple security issues and there is a new maintainer release for 2 dependencies as well, I recommend that the project sets up dependabot for the project to keep on top of the dependencies

### CODE REVIEW

**Comment by Dogfalo** [comment]
We can't merge this as the checks are failing

**Comment by L1ghtn1ng** [comment]
From what I can tell this is due to the updated dependencies and once merge it should work, as it stands currently there are security issues with the current dependencies that materialize uses
________________________________

**Comment by L1ghtn1ng** [comment]
@Dogfalo I did try to fix the issue that travis was flagging about regarding https://github.com/browserslist/browserslist#readme with this https://github.com/Dogfalo/materialize/pull/6241/commits/ad75b6cde7388d77c7233ab2f6d2b954319478d1 but it has not worked. Could you have a look as I do not know what I am doing, thanks

**Comment by DanielRuf** [comment]
This breaks the tests, we should handle this directly here. Not through this PR.

**Comment by DanielRuf** [comment]
> L1ghtn1ng:v1-dev

Also please use a separate branch at your fork and for the PR as source - as this will cause conflicts. You would have to rebase your whole branch.

**Comment by L1ghtn1ng** [comment]
@DanielRuf I am not modifying anything else as all I am doing is submitting dep updates and that is it. Also github is reporting that there is no conflicts, I have a few more dep updates that I will push shortly that have rolled in but this should be a very high priority to get this PR merged etc to not have materialize be vulnerable

**Comment by DanielRuf** [comment]
You are directly pushing to the original `v1-dev` branch which is an antipattern and will not work anymore when the upstream repo (Dogfalo/materialize) has new commits on the same branch.

This will cause conflicts, even more for lockfiles and package.json.

**Comment by DanielRuf** [comment]
PS: lockfiles are not used by libraries / npm, for example in this case. So package.json changes are sufficient.

**Comment by DanielRuf** [comment]
PPS: dev dependencies are not really relevant

**Comment by DanielRuf** [comment]
But a nice yakshaving / bikeshedding PR.

**Comment by L1ghtn1ng** [comment]
This is how dependabot does its changes for npm packages and I understand the git stuff but this was meant to be a quick thing that I thought would of gotten merged ages ago. Fortunately there are no changes to cause conflicts if this gets merged now

**Comment by L1ghtn1ng** [comment]
Hopefully will have package.json updates now as have changed how dependabot does things so it does the lock as well as the packakge.json just kicked off a job now

**Comment by L1ghtn1ng** [comment]
Can we please get this merged, this fixes a lot of security issues !!!

**Comment by DanielRuf** [comment]
> Can we please get this merged, this fixes a lot of security issues !!!

My last comment is still valid, devDependencies are not security relevant and you bump things without checking if anything breaks. Please take a look at the breaking CI build. If we do these updates we will update dependabot on the fork.

**Comment by DanielRuf** [comment]
> Can we please get this merged, this fixes a lot of security issues !!!

My last comment is still valid, devDependencies are not security relevant and you bump things without checking if anything breaks. Please take a look at the breaking CI build. If we do these updates we will update dependabot on the fork.

And using the same branch is discouraged as this will break when there are new commits on the v1-dev branch.

**Comment by L1ghtn1ng** [comment]
I do not know how to fix the ci stuff and security issues are security issues no matter what they are used for and should be resolved to protect against these issues
________________________________

**Comment by DanielRuf** [comment]
devDependencies are only for building materialize.js and never land in the materialize.js file or on any production server.

We will apply needed updates (if relevant) one by one on the fork but not like this (all at once and breaking stuff).

**Pull request closed without merging**
