### PR TITLE
Added option to rewrite data in autocomplete

### PR DESCRIPTION
**Pull request by leonardobazico**
Prior to calling the autocomplete function to update the data, it was added to the end of the existing list.
You can now overwrite the data by calling the autocomplete function again.

```
$('input.autocomplete').autocomplete({
    data: {
      "Apple": null,
      "Microsoft": null,
      "Google": 'http://placehold.it/250x250'
    },
    rewrite: true
  });
```

### CODE REVIEW

**Comment by thebiltheory** [comment]
Awesome! I had the same problem, I ended up with a bunch of <ul> autocompletes. Another thing would be good to go through the list with the keyboard @leonardobazico.

**Comment by leonardobazico** [comment]
@thebiltheory, it's really frustrating not being able go through the list with the keyboard.

**Comment by nuplo** [comment]
Hey, today I improved code for autocomplete - added arrow keys usage, more advanced replacing data and some other things. Look at https://github.com/Dogfalo/materialize/pull/3694

**Comment by arlowhite** [comment]
Maybe this PR should be closed if #3694 replaces it?

**Comment by leonardobazico** [comment]
@arlowhite #3694 is a great PR, but has some bugs. It doesn't rewrite the list of autocomplete.

captura de tela 2016-10-19 as 09 00 05
captura de tela 2016-10-19 as 08 56 45

I will merge my PR with #3694.

**Comment by thebiltheory** [comment]
@leonardobazico Happened exactly the same to me. You're probably instantiating a new autocomplete on each keypress.

**Pull request closed without merging**
