### PR TITLE
bugfix: use after instead of append for thumb on range

### PR DESCRIPTION
**Pull request by Chun-Yang**
Solve issue https://github.com/Dogfalo/materialize/issues/1748

### CODE REVIEW

**Comment by mitar** [comment]
I can confirm that this pull request fixes the issue with using range element in Meteor. Thanks!

**Comment by mitar** [comment]
Was that merged?

**Comment by Chun-Yang** [comment]
This is not merged. I updated my fork to keep it up-to-date. The issue is closed automatically. I will create another PR later.

**Comment by mitar** [comment]
Yea, don't make pull requests from the `master` branch. Make a feature branch and make a pull request from there.

**Comment by Chun-Yang** [comment]
Lesson learnt. :smile:

**Pull request closed without merging**
