### PR TITLE
Upgrade to jQuery v3

### PR DESCRIPTION
**Pull request by ManuZiD**
Goal was to migrate the project to jQuery v3.

Two issues have to been fixed.

1. jQuery.fn.bind() and jQuery.fn.unbind(): These methods have been
deprecated since jQuery v3.0 and they should be replaced with on() and
off(). Affected files: search.js, dropdown.js, sideNav.js, slider.js,
transitions.js.

2. jQuery.easing.easeOutQuart should use only first argument: the extra
parameters that the easing functions expected are now deprecated. Read
https://jquery.com/upgrade-guide/3.0/#deprecated-additional-easing-funct
ion-parameters for details. On https://github.com/gdsmith/jquery.easing
there is a newer version. Added jquery.easing with version 1.4. Update
Gruntfile.js to match the newer version.

### CODE REVIEW

**Comment by tomscholz** [comment]
You forgot to upgrade the dependence in the package.json

**Comment by DanielRuf** [comment]
What about deleting jquery.easing.1.3?

@tomscholz no, the caret also upgrades the major version. If people are bound to jQuery 2, they can still use it this way. If not, npm uses 3.x.y ;-)

**Comment by tomscholz** [comment]
With which jQuery version did you test? The latest, 3.2.1?

**Comment by ManuZiD** [comment]
@DanielRuf yes, you right that version can be deleted.

@tomscholz i tested it with the 3.0.0

`<script src="https://code.jquery.com/jquery-3.0.0.js"></script>
<script src="https://code.jquery.com/jquery-migrate-3.0.0.js"></script>`

**Comment by tomscholz** [comment]
This should also fix https://github.com/Dogfalo/materialize/pull/2450

**Comment by tomscholz** [comment]
or not ;) https://travis-ci.org/Dogfalo/materialize/builds/225250212

**Comment by DanielRuf** [comment]
Sure, the other issue is fu'ixed but there might be some issue because the travis task does not install jquery or did I miss something?

**Comment by tomscholz** [comment]
@DanielRuf It sure does https://github.com/Dogfalo/materialize/blob/master/_SpecRunner.html#L27

**Comment by DanielRuf** [comment]
Right, oversaw this. Just jQuery 3 incompatible components 
@ManuZiD please take a look at the failing tests.

**Comment by DanielRuf** [comment]
At least the chips test was fixed in https://github.com/Dogfalo/materialize/pull/4434 (should be, still unmerged).

**Comment by ManuZiD** [comment]
I'm not able to run the test on my machine. If I start it with `grunt travis` it hangs on 

`Running "jasmine:components" (jasmine) task
Testing jasmine specs via PhantomJS`

Any suggestions?

**Comment by DanielRuf** [comment]
Not sure. Are all dependencies installed? Is PhantomJS blocked by some security solution? Can you test the tests manually?

**Comment by tomscholz** [comment]
I actually have the same issue. MacOs 10.11.1 . You can try `grunt monitor` and then access the _SpecRunner.html file, but it's not the same as running it with phantomjs

**Comment by DanielRuf** [comment]
So `grunt travis --filter=component_name` would not work?

https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md

**Comment by DanielRuf** [comment]
Can you triage the cause of this?

**Comment by ManuZiD** [comment]
Sorry for the late response but I'm now at home. Now I can eliminate the point with network issues. I have do a completely fresh checkout (master), open the terminal, type in `npm install` and after this `grunt travis`. Same result, it hangs at
`Running "jasmine:components" (jasmine) task

Testing jasmine specs via PhantomJS`

**Comment by DanielRuf** [comment]
Can you run the grunt task with the verbose mode using `-v`?

This should shed some light on what is happening in the background.

**Comment by ManuZiD** [comment]
Ok, now I'm waiting 10 minutes and this is finally the output from `grunt travis -v`

`Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK

Registering "grunt-contrib-watch" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-watch/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-watch/package.json...OK
Loading "watch.js" tasks...OK
+ watch

Registering "grunt-contrib-copy" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-copy/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-copy/package.json...OK
Loading "copy.js" tasks...OK
+ copy

Registering "grunt-sass" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-sass/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-sass/package.json...OK

node-sass	3.13.1	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]

Loading "sass.js" tasks...OK
+ sass

Registering "grunt-contrib-concat" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-concat/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-concat/package.json...OK
Loading "concat.js" tasks...OK
+ concat

Registering "grunt-contrib-uglify" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-uglify/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-uglify/package.json...OK
Loading "uglify.js" tasks...OK
+ uglify

Registering "grunt-contrib-compress" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-compress/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-compress/package.json...OK
Loading "compress.js" tasks...OK
+ compress

Registering "grunt-contrib-clean" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-clean/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-clean/package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-contrib-jade" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-jade/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-jade/package.json...OK
Loading "jade.js" tasks...OK
+ jade

Registering "grunt-concurrent" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-concurrent/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-concurrent/package.json...OK
Loading "concurrent.js" tasks...OK
+ concurrent

Registering "grunt-notify" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-notify/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-notify/package.json...OK
Loading "notify.js" tasks...OK
+ notify
Loading "notify_hooks.js" tasks...OK
+ notify_hooks

Registering "grunt-text-replace" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-text-replace/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-text-replace/package.json...OK
Loading "text-replace.js" tasks...OK
+ replace

Registering "grunt-banner" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-banner/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-banner/package.json...OK
Loading "usebanner.js" tasks...OK
+ usebanner

Registering "grunt-rename" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-rename/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-rename/package.json...OK
Loading "rename.js" tasks...OK
+ rename

Registering "grunt-remove-logging" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-remove-logging/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-remove-logging/package.json...OK
Loading "grunt-remove-logging.js" tasks...OK
+ removelogging

Registering "grunt-browser-sync" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-browser-sync/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-browser-sync/package.json...OK
Loading "browser-sync.js" tasks...OK
+ browserSync, bsNotify, bsReload

Registering "grunt-contrib-jasmine" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-jasmine/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-jasmine/package.json...OK
Loading "jasmine.js" tasks...OK
+ jasmine

Registering "grunt-postcss" local Npm module tasks.
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-postcss/package.json...OK
Parsing /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-postcss/package.json...OK
Loading "postcss.js" tasks...OK
+ postcss
Loading "Gruntfile.js" tasks...OK
+ jade_compile, js_compile, lint, monitor, release, sass_compile, server, travis

Running tasks: travis

Running "travis" task

Running "js_compile" task

Running "concat:temp" (concat) task
Verifying property concat.temp exists in config...OK
Files: js/initial.js, js/jquery.easing.1.3.js, js/animation.js, js/velocity.min.js, js/hammer.min.js, js/jquery.hammer.js, js/global.js, js/collapsible.js, js/dropdown.js, js/modal.js, js/materialbox.js, js/parallax.js, js/tabs.js, js/tooltip.js, js/waves.js, js/toasts.js, js/sideNav.js, js/scrollspy.js, js/forms.js, js/slider.js, js/cards.js, js/chips.js, js/pushpin.js, js/buttons.js, js/transitions.js, js/scrollFire.js, js/date_picker/picker.js, js/date_picker/picker.date.js, js/character_counter.js, js/carousel.js, js/tapTarget.js -> temp/js/materialize.js
Options: separator=";", banner="", footer="", stripBanners=false, process=false, sourceMap=false, sourceMapName=undefined, sourceMapStyle="embed"
Reading js/initial.js...OK
Reading js/jquery.easing.1.3.js...OK
Reading js/animation.js...OK
Reading js/velocity.min.js...OK
Reading js/hammer.min.js...OK
Reading js/jquery.hammer.js...OK
Reading js/global.js...OK
Reading js/collapsible.js...OK
Reading js/dropdown.js...OK
Reading js/modal.js...OK
Reading js/materialbox.js...OK
Reading js/parallax.js...OK
Reading js/tabs.js...OK
Reading js/tooltip.js...OK
Reading js/waves.js...OK
Reading js/toasts.js...OK
Reading js/sideNav.js...OK
Reading js/scrollspy.js...OK
Reading js/forms.js...OK
Reading js/slider.js...OK
Reading js/cards.js...OK
Reading js/chips.js...OK
Reading js/pushpin.js...OK
Reading js/buttons.js...OK
Reading js/transitions.js...OK
Reading js/scrollFire.js...OK
Reading js/date_picker/picker.js...OK
Reading js/date_picker/picker.date.js...OK
Reading js/character_counter.js...OK
Reading js/carousel.js...OK
Reading js/tapTarget.js...OK
Writing temp/js/materialize.js...OK
File temp/js/materialize.js created.

Running "uglify:bin" (uglify) task
Verifying property uglify.bin exists in config...OK
Files: temp/js/materialize.js -> bin/materialize.js
Options: banner="", footer="", compress={"warnings":false}, mangle={}, beautify=false, report="min", expression=false, maxLineLen=32000, ASCIIOnly=false, screwIE8=false, quoteStyle=0
Minifying with UglifyJS...Reading temp/js/materialize.js...OK
OK
Writing bin/materialize.js...OK
File bin/materialize.js created: 325.98 kB → 148.69 kB
>> 1 file created.

Running "notify:js_compile" (notify) task
Verifying property notify.js_compile exists in config...OK
File: [no files]
Options: title="Materialize", message="JS Compiled!", enabled, success, duration=1
>> [grunt-notify] growl: growlnotify wasn't found. If you were hoping to use Growl, make you sure you have their command line script called Growlnotify. Mac: http://growl.info/downloads or Windows: http://www.growlforwindows.com/gfw/help/growlnotify.aspx and put it in your path. You should be able to type growlnotify --version and get something back.
>> [grunt-notify] IS_WINDOWS: false
>> [grunt-notify] PROGRAM_FILES: undefined
>> [grunt-notify] PROGRAM_FILES_X86: undefined
>> [grunt-notify] fullPathToApplication: false
>> [grunt-notify] snarl: Snarl not available for this OS.
>> [grunt-notify] os: Darwin
>> [grunt-notify] version: 16.5.0
>> [grunt-notify] IS_MAC: true
>> [grunt-notify] MOUNTAIN_LION: true
>> [grunt-notify] notification_center: Will use Notification Center
>> [notification-center] cmd: /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-notify/bin/Grunt.app/Contents/MacOS/Grunt
>> [notification-center] args: -title Materialize -message JS Compiled!

Running "clean:temp" (clean) task
Verifying property clean.temp exists in config...OK
Files: temp/
Options: force=false, no-write=false
Cleaning temp/...
>> 1 path cleaned.

Running "sass_compile" task

Running "sass:gh" (sass) task
Verifying property sass.gh exists in config...OK
Files: sass/ghpages-materialize.scss -> css/ghpages-materialize.css
Options: precision=10, outputStyle="compressed", sourcemap=false
Writing css/ghpages-materialize.css...OK

Running "sass:bin" (sass) task
Verifying property sass.bin exists in config...OK
Files: sass/materialize.scss -> bin/materialize.css
Options: precision=10, outputStyle="expanded", sourcemap=false
Writing bin/materialize.css...OK

Running "postcss:gh" (postcss) task
Verifying property postcss.gh exists in config...OK
Files: css/ghpages-materialize.css
Options: processors=[null], map=false, diff=false, safe=false, failOnError=false, writeDest
Reading css/ghpages-materialize.css...OK
Writing css/ghpages-materialize.css...OK
File css/ghpages-materialize.css created.
>> 1 processed stylesheet created.

Running "postcss:bin" (postcss) task
Verifying property postcss.bin exists in config...OK
Files: bin/materialize.css
Options: processors=[null], map=false, diff=false, safe=false, failOnError=false, writeDest
Reading bin/materialize.css...OK
Writing bin/materialize.css...OK
File bin/materialize.css created.
>> 1 processed stylesheet created.

Running "notify:sass_compile" (notify) task
Verifying property notify.sass_compile exists in config...OK
File: [no files]
Options: title="Materialize", message="Sass Compiled!", enabled, success, duration=1
>> [notification-center] cmd: /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-notify/bin/Grunt.app/Contents/MacOS/Grunt
>> [notification-center] args: -title Materialize -message Sass Compiled!

Running "jasmine" task

Running "jasmine:components" (jasmine) task
Verifying property jasmine.components exists in config...OK
Files: bin/materialize.js
Options: version="2.0.1", timeout=10000, styles="bin/materialize.css", specs="tests/spec/**/*Spec.js", helpers="tests/spec/helper.js", vendor=["node_modules/jquery/dist/jquery.min.js","node_modules/jasmine-jquery/lib/jasmine-jquery.js"], polyfills=[], outfile="_SpecRunner.html", host="", template="/Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-jasmine/tasks/jasmine/templates/DefaultRunner.tmpl", templateOptions={}, junit={}, ignoreEmpty=false, display="full", summary=false, keepRunner
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-jasmine/tasks/jasmine/reporters/PhantomReporter.js...OK
Writing .grunt/grunt-contrib-jasmine/reporter.js...OK
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/jasmine-core/lib/jasmine-core/jasmine.css...OK
Writing .grunt/grunt-contrib-jasmine/jasmine.css...OK
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/jasmine-core/lib/jasmine-core/jasmine.js...OK
Writing .grunt/grunt-contrib-jasmine/jasmine.js...OK
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/jasmine-core/lib/jasmine-core/jasmine-html.js...OK
Writing .grunt/grunt-contrib-jasmine/jasmine-html.js...OK
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/jasmine-core/lib/jasmine-core/json2.js...OK
Writing .grunt/grunt-contrib-jasmine/json2.js...OK
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/jasmine-core/lib/jasmine-core/boot.js...OK
Writing .grunt/grunt-contrib-jasmine/boot.js...OK
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/jasmine-core/images/jasmine_favicon.png...OK
Writing .grunt/grunt-contrib-jasmine/jasmine_favicon.png...OK
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/es5-shim/es5-shim.js...OK
Writing .grunt/grunt-contrib-jasmine/es5-shim.js...OK
Reading /Users/emanuelzienecker/Documents/GitRepos/mat/node_modules/grunt-contrib-jasmine/tasks/jasmine/templates/DefaultRunner.tmpl...OK
Processing source...OK
Writing _SpecRunner.html...OK

Testing jasmine specs via phantom`

**Comment by DanielRuf** [comment]
Can you please put this in a code box with three backticks at the start and end?

**Comment by tomscholz** [comment]
Done

**Comment by DanielRuf** [comment]
Can we safely upgrade to PhantomJS 2? I guess this is some crash / segmentation fault and it was silently killed or hangs. @tomscholz did the PhantomJS task run on your system before?

**Comment by ManuZiD** [comment]
@DanielRuf where you read that 2.5 is the current version? On the page (http://phantomjs.org/download.html) and in the link you provide they say 2.1.1 is the current version. with this it's not working too

**Comment by DanielRuf** [comment]
Minor is 5, Major 2 => 2.5

https://github.com/ariya/phantomjs/blob/master/src/consts.h

**Comment by DanielRuf** [comment]
At least 2.1 (2016) should run. How did you upgrade the PhantomJS version?

http://phantomjs.org/download.html

**Comment by DanielRuf** [comment]
For me the PhantomJS looks a bit inactive. You could try a build from master. Or we have to find an alternative.

**Comment by DanielRuf** [comment]
Here is a 2.5 beta version: https://bitbucket.org/ariya/phantomjs/downloads/

**Comment by DanielRuf** [comment]
In this case you could only test on a Linux VM or test the files and scripts manually using the unminified materialize.js, the markup from the fixture files and your browser.

**Comment by ManuZiD** [comment]
I edit the phantomjs version in the package.json file. I'm new to this, I have no idea what now I do with the beta. grunt takes the phantom version from the package.json, I'm right? Now how include the 2.5 beta?

**Comment by DanielRuf** [comment]
No, you have to change it to `^2.1.1` (but at least `^2.0.0` and run `npm update phantomjs`

**Comment by DanielRuf** [comment]
The steps for 2.5 beta might be too difficult. Normally it should be enough to replace all files in the phantomjs directory under npm_modules with the new files but in this case it might be better to setup 2.5 beta as standalone, configure it manually and run the test.

But first try to update to a new phantomjs version.

**Comment by tomscholz** [comment]
I updated to 2.1.1 and end up with the same result as [here](https://github.com/Dogfalo/materialize/pull/4587#issuecomment-297101104)

**Comment by tomscholz** [comment]
But I just spotted this:
```shell
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
```

**Comment by ManuZiD** [comment]
this didn't work for me 

@tomscholz have you tried the 2.5.0-beta?

**Comment by DanielRuf** [comment]
Latest phantomjs-prebuilt release is 2.1.14 which still fails as I said =)

https://www.npmjs.com/package/phantomjs-prebuilt

**Comment by tomscholz** [comment]
Well, I have to learn for an exam tomorrow :) Wish me luck ;) I will continue looking into it tomorrow...

**Comment by DanielRuf** [comment]
Good luck!

**Comment by DanielRuf** [comment]
@ManuZiD was `npm install phantomjs-prebuilt` without any success?

**Comment by ManuZiD** [comment]
@tomscholz good luck, see ya tomorrow

@DanielRuf I'm confused because I typed in the command you suggest and if i type in `phantomjs --version` I get still the 2.1.1 ... this is the print of `npm install phantomjs-prebuilt`

```shell
/usr/local/bin/phantomjs -> /usr/local/lib/node_modules/phantomjs-prebuilt/bin/phantomjs

> phantomjs-prebuilt@2.1.14 install /usr/local/lib/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Looks like an `npm install -g`
Could not link global install, skipping...
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
Saving to /tmp/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...
  [========================================] 99%
Received 16746K total.
Extracting zip contents
Removing /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1493148122863/phantomjs-2.1.1-macosx -> /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
/usr/local/lib
└─┬ phantomjs-prebuilt@2.1.14 
  ├── es6-promise@4.0.5 
  ├─┬ extract-zip@1.5.0 
  │ ├─┬ concat-stream@1.5.0 
  │ │ ├── inherits@2.0.3 
  │ │ ├─┬ readable-stream@2.0.6 
  │ │ │ ├── core-util-is@1.0.2 
  │ │ │ ├── isarray@1.0.0 
  │ │ │ ├── process-nextick-args@1.0.7 
  │ │ │ ├── string_decoder@0.10.31 
  │ │ │ └── util-deprecate@1.0.2 
  │ │ └── typedarray@0.0.6 
  │ ├── debug@0.7.4 
  │ ├─┬ mkdirp@0.5.0 
  │ │ └── minimist@0.0.8 
  │ └─┬ yauzl@2.4.1 
  │   └─┬ fd-slicer@1.0.1 
  │     └── pend@1.2.0 
  ├─┬ fs-extra@1.0.0 
  │ ├── graceful-fs@4.1.11 
  │ ├── jsonfile@2.4.0 
  │ └── klaw@1.3.1 
  ├─┬ hasha@2.2.0 
  │ ├── is-stream@1.1.0 
  │ └─┬ pinkie-promise@2.0.1 
  │   └── pinkie@2.0.4 
  ├── kew@0.7.0 
  ├── progress@1.1.8 
  ├─┬ request@2.79.0 
  │ ├── aws-sign2@0.6.0 
  │ ├── aws4@1.6.0 
  │ ├── caseless@0.11.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── extend@3.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@2.1.4 
  │ │ └── asynckit@0.4.0 
  │ ├─┬ har-validator@2.0.6 
  │ │ ├─┬ chalk@1.1.3 
  │ │ │ ├── ansi-styles@2.2.1 
  │ │ │ ├── escape-string-regexp@1.0.5 
  │ │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ │ └── ansi-regex@2.1.1 
  │ │ │ ├── strip-ansi@3.0.1 
  │ │ │ └── supports-color@2.0.0 
  │ │ ├─┬ commander@2.9.0 
  │ │ │ └── graceful-readlink@1.0.1 
  │ │ └─┬ is-my-json-valid@2.16.0 
  │ │   ├── generate-function@2.0.0 
  │ │   ├─┬ generate-object-property@1.2.0 
  │ │   │ └── is-property@1.0.2 
  │ │   ├── jsonpointer@4.0.1 
  │ │   └── xtend@4.0.1 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.1 
  │ │ ├── assert-plus@0.2.0 
  │ │ ├─┬ jsprim@1.4.0 
  │ │ │ ├── assert-plus@1.0.0 
  │ │ │ ├── extsprintf@1.0.2 
  │ │ │ ├── json-schema@0.2.3 
  │ │ │ └── verror@1.3.6 
  │ │ └─┬ sshpk@1.13.0 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@1.0.0 
  │ │   ├── bcrypt-pbkdf@1.0.1 
  │ │   ├─┬ dashdash@1.14.1 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├─┬ getpass@0.1.6 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── jodid25519@1.0.2 
  │ │   ├── jsbn@0.1.1 
  │ │   └── tweetnacl@0.14.5 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.1.15 
  │ │ └── mime-db@1.27.0 
  │ ├── oauth-sign@0.8.2 
  │ ├── qs@6.3.2 
  │ ├── stringstream@0.0.5 
  │ ├─┬ tough-cookie@2.3.2 
  │ │ └── punycode@1.4.1 
  │ ├── tunnel-agent@0.4.3 
  │ └── uuid@3.0.1 
  ├─┬ request-progress@2.0.1 
  │ └── throttleit@1.0.0 
  └─┬ which@1.2.14 
    └── isexe@2.0.0 
```

**Comment by DanielRuf** [comment]
Unfortunately there is no newer binary release https://github.com/Medium/phantomjs/releases?after=v2.1.5

**Comment by ManuZiD** [comment]
Thanks I go with a vm. I hope there is a alternative

**Comment by DanielRuf** [comment]
change 
https://github.com/Dogfalo/materialize/blob/master/tests/spec/select/selectSpec.js#L105
to
`expect(browserSelect.val()).toEqual([], 'Actual select element should be empty because none chosen.');`

see https://api.jquery.com/val/

> **As of jQuery 3.0**, if no options are selected, it returns an empty array; **prior to jQuery 3.0**, it returns null.

**Comment by tomscholz** [comment]
LALALALLA. I know, I know. I said I have to learn. **BUT** I found the problem.
Update the `grunt-contrib-jasmine` to version `1.1.0` then phantomjs works

**Comment by DanielRuf** [comment]
So https://github.com/karma-runner/karma-phantomjs-launcher/issues/138#issuecomment-255579589 from was the solution? https://github.com/Dogfalo/materialize/pull/4587#issuecomment-297136459

**Comment by DanielRuf** [comment]
The test for the cards should be like this
```JavaScript
describe( "Cards", function () {
  var reveal;

  beforeEach(function() {
    loadFixtures('cards/cardsFixture.html');
  });

  describe("reveal cards", function () {
    var revealCard;

    beforeEach(function() {
      revealCard = $('.card.reveal');
    });

    it("should have a hidden card-reveal", function (done) {
      var revealDiv = revealCard.find('.card-reveal');
      var activator = revealCard.find('.activator');

      expect(revealDiv).toBeHidden('reveal div should be hidden initially');

      setTimeout(function() {
        activator.click();
        
        setTimeout(function() {
          expect(revealDiv).toBeVisible('reveal did not appear after activator was clicked.');
        
          // Check revealDiv covers reveal card.
          expect(revealDiv.outerWidth()).toEqual(revealCard.outerWidth(), 'activator was not as wide as reveal card.');
          expect(revealDiv.outerHeight()).toEqual(revealCard.outerHeight(), 'activator was not as high as reveal card.');
          expect(revealDiv.offset().top).toEqual(revealCard.offset().top, 'activator was not as in the same y as reveal card.');
          expect(revealDiv.offset().left).toEqual(revealCard.offset().left, 'activator was not as in the same x as reveal card.');
        
          done();
        }, 400);
      }, 400);

    });
  });

  describe("image cards", function () {
    var imageCard;

    beforeEach(function() {
      imageCard = $('.card.image');
    });

    it("should have an image that fills to full width of card", function () {
      var image = imageCard.find('.card-image > img');

      expect(image.outerWidth()).toEqual(imageCard.outerWidth(), 'image does not fill width of card');
      expect(image.offset().top).toEqual(imageCard.offset().top, 'image was not as in the same y as card.');
    });
  });


  describe("sized cards", function () {
    var small, medium, large;

    beforeEach(function() {
      small = $('.card.small');
      medium = $('.card.medium');
      large = $('.card.large');
    });

    it("should have small card dimensions", function () {
      var cardImage = small.find('.card-image');
      var cardContent = small.find('.card-content');
      var cardAction = small.find('.card-action');

      expect(small.outerHeight()).toEqual(300, 'small card should be 300px high');
      expect(cardImage.outerHeight()).toBeLessThan(181, 'small image should be <= 180px or 60% high');
      expect(cardContent.outerHeight()).toBeLessThan(121, 'small content should be <= 120px or 40% high');
      expect(cardAction.offset().top + cardAction.outerHeight())
        .toEqual(small.offset().top + small.outerHeight(), 'small action should be at bottom of card');
    });

    it("should have medium card dimensions", function () {
      var cardImage = medium.find('.card-image');
      var cardContent = medium.find('.card-content');
      var cardAction = medium.find('.card-action');

      expect(medium.outerHeight()).toEqual(400, 'medium card should be 400px high');
      expect(cardImage.outerHeight()).toBeLessThan(241, 'medium image should be <= 240 or 60% high');
      expect(cardContent.outerHeight()).toBeLessThan(161, 'medium content should be <= 160px or 40% high');
      expect(cardAction.offset().top + cardAction.outerHeight())
        .toEqual(medium.offset().top + medium.outerHeight(), 'medium action should be at bottom of card');
    });

    it("should have large card dimensions", function () {
      var cardImage = large.find('.card-image');
      var cardContent = large.find('.card-content');
      var cardAction = large.find('.card-action');

      expect(large.outerHeight()).toEqual(500, 'large card should be 500px high');
      expect(cardImage.outerHeight()).toBeLessThan(301, 'large image should be <= 300 or 60% high');
      expect(cardContent.outerHeight()).toBeLessThan(201, 'large content should be <= 200 or 40% high');
      expect(cardAction.offset().top + cardAction.outerHeight())
        .toEqual(large.offset().top + large.outerHeight(), 'large action should be at bottom of card');
    });
  });

});
```

**Comment by DanielRuf** [comment]
Same for the autocomplete test as it seems:

```JavaScript
describe("Autocomplete Plugin", function () {
  beforeEach(function() {
    loadFixtures('autocomplete/autocompleteFixture.html');
    setTimeout(function() {
      $('input.autocomplete').autocomplete({
        data: {
          "Apple": null,
          "Microsoft": null,
          "Google": 'http://placehold.it/250x250'
        }
      });
    }, 400);
  });

  describe("Autocomplete", function () {
    // var browserSelect, normalInput, normalDropdown;

    // beforeEach(function() {
    //   browserSelect = $('select.normal');
    // });

    it("should work with multiple initializations", function () {
      var $normal = $('#normal-autocomplete');
      var $parent = $normal.parent();
      setTimeout(function() {
        $normal.autocomplete({ data: {"hi": null} });
        $normal.autocomplete({ data: {"hi": null} });
        $normal.autocomplete({ data: {"hi": null} });
        $normal.autocomplete({
          data: {
            "Apple": null,
            "Microsoft": null,
            "Google": 'http://placehold.it/250x250'
          }
        });
        
        var $autocompleteEl = $parent.find('.autocomplete-content');
        var autocompleteEvents = $._data($normal[0], 'events');
        
        expect($autocompleteEl.length).toEqual(1, 'Should dynamically generate autocomplete structure.');
        expect(autocompleteEvents.keyup.length).toEqual(1, 'Should only bind 1 keyup handler on input');
        // setTimeout(function() {
        //   done();
      }, 400);
    });

    it("should limit results if option is set", function (done) {
      var $limited = $('#limited-autocomplete');
      var data = {};
      for (var i = 100; i >= 0; i--) {
        var randString = 'a' + Math.random().toString(36).substring(20);
        data[randString] = null;
      }

      $limited.autocomplete({
        data: data,
        limit: 20
      });

      $limited.focus();
      $limited.val('a');
      $limited.trigger('keyup');

      var $autocompleteEl = $limited.parent().find('.autocomplete-content');
      setTimeout(function() {
        expect($autocompleteEl.children().length).toBeLessThan(21, 'Results should be at max the set limit');
        done();
      }, 200);

    });
  });

});

```

**Comment by DanielRuf** [comment]
Awesome, the build has no more errors =)

**Comment by tomscholz** [comment]
@DanielRuf There still seems some error with jQuery. https://travis-ci.org/Dogfalo/materialize/builds/225893292#L658, but the tests run successfully

**Comment by ManuZiD** [comment]
@tomscholz that's confused me. On my machine I doesn't get these errors

**Comment by DanielRuf** [comment]
@tomscholz @ManuZiD ignore this error, this was there before the jQuery 3 change and is fixed by another PR which is still unmerged.

**Comment by acburst** [comment]
Will this force people to use jQuery 3? or just make it compatible. It looks good to me anyways. Just need to resolve some conflicts with recent dependency changes

**Comment by acburst** [comment]
Also for future reference, its a lot easier to review pull requests in small chunks. I would be comfortable merging in just a pull request of the removal of binds as a separate thing to all the dependency changes. It makes it some changes that can be added immediately aren't held up by other parts of the pull request.

**Comment by tomscholz** [comment]
@ManuZiD

**Comment by DanielRuf** [comment]
Awesome =)

**Pull request merged**
