### PR TITLE
More usefull to select a class

### PR DESCRIPTION
**Pull request by jonathanpath**
Otherwise, I can't use nav for anther personnel components.

### CODE REVIEW

**Comment by carlosperate** [comment]
I'm not sure this is a such a good idea, as it would break pretty much everybody's implementation of materialize.

**Comment by jonathanpath** [comment]
Why not replace nav by .nav everywhere it is used ?

**Comment by ipalaus** [comment]
Because you can't replace it on people's websites. This is a breaking change and it's not backwards-compatible.

**Comment by carlosperate** [comment]
Closing as this is a breaking change.

**Pull request closed without merging**
