### PR TITLE
Chips js basic

### PR DESCRIPTION
**Pull request by alejandrovasta**

### CODE REVIEW

**Comment by alejandrovasta** [comment]
@acburst I checked locally that the tests passed well without errors. I had used the chips branch previous to this PR.

**Comment by acburst** [comment]
Because of the size of this PR it might take a while for us to properly merge this in. Also the holiday season is coming up for us which will also cause some delays.

**Comment by alejandrovasta** [comment]
No problem, when you can @acburst. I tried to match the material basic functionality. The idea here is to finish it with the dropdown option for autocompleting and other cool stuff

**Comment by acburst** [comment]
Finally merged this in. Thanks so much for your help. I cleaned up the code a bit and simplified things a little.

**Pull request merged**
