### PR TITLE
updated readme for pull requests

### PR DESCRIPTION
**Pull request by HellerCommaA**
Minor remarks on contributor guidelines.

### CODE REVIEW

**Comment by Dogfalo** [comment]
Please add this to CONTRIBUTING.md instead

**Comment by HellerCommaA** [comment]
Updated.  Added link in README.md to contrib.md

**Comment by Dogfalo** [comment]
This still isn't quite right, the contributing link is not valid

**Comment by HellerCommaA** [comment]
@Dogfalo MD is fixed

**Comment by Dogfalo** [comment]
Great thanks!

**Pull request merged**
