### PR TITLE
Fixed Extra End </i> Tag

### PR DESCRIPTION
**Pull request by danielhickman**
The fixed multi FAB example had an extra `</i>`.

### CODE REVIEW

**Comment by danielhickman** [comment]
`<li><a class="btn-floating red"><i class="material-icons">insert_chart</i></i></a></li>` Is this line without the HTML entities.

**Comment by carlosperate** [comment]
Please, when updating the documentation edit on the the jade page-content pages as indicated in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file.

**Comment by danielhickman** [comment]
@carlosperate Apologies, I missed that when reading it.

**Comment by tomscholz** [comment]
I don't see the problem

**Comment by danielhickman** [comment]
Looks like it has been fixed since I originally made this pull request.

**Pull request closed without merging**
