### PR TITLE
Date- and Timepicker new layout according to md specs + addition of timepicker

### PR DESCRIPTION
**Pull request by philipraets**
Reworked layout for datepicker to be like the specs including a landscape and portrait-layout
Added a Timepicker with the same layout
Added timepicker to docs

landscape:
datepicker landscape
timepicker lansdscape

portrait:
datepicker protrait
timepicker portrait

### CODE REVIEW

**Comment by smileytechguy** [comment]
This is great!  Can we get a demo?

**Comment by philipraets** [comment]
I've created a codepen: http://codepen.io/anon/pen/woqevN

**Comment by smileytechguy** [comment]
Nice!! Only thing I'd add is AM/PM options (rather than 24 hour time) and the ability to change the color.

**Comment by philipraets** [comment]
If you change the option "twelvehour" to true, there will be AM/PM (I live in Belgium, we don't use AM/PM, but it's there :-) )
to change the color, I use classes like .green-picker

css example:
.picker__holder.green-picker .picker__date-display,
.picker__holder.green-picker .picker__day--selected,
.picker__holder.green-picker .picker__day--selected:hover,
.picker__holder.green-picker .picker--focused .picker__day--selected {
  background: #4caf50 none repeat scroll 0 0;
}

**Comment by NonameSLdev** [comment]
While this is very nice, you're not suppose to edit the files in bin. For css edit the scss files and for js edit the files in the /js/ directory. Make your changes in the correct directories so it could be considered to be accepted.
I have some better looking css to combine your js code with, but this is great other than that.

**Comment by philipraets** [comment]
I think those files were because of compiling, but I'm going to clean up my repository, create a new branch, recreate the date- and timepicker and try a new pull request (hopefully with only the correct changes :-) )

**Comment by smileytechguy** [comment]
@philipraets Awesome, thanks!  Can you mention me in the PR so I can get notified?
Thanks

**Comment by philipraets** [comment]
the new PR is #4445 and this is based on the latest materialize code

**Pull request closed without merging**
