### PR TITLE
Add input suffix

### PR DESCRIPTION
**Pull request by nathankoop**
Add suffix which looks just like existing prefix except it follows the
input.

### CODE REVIEW

**Comment by nathankoop** [comment]
Per #2489: Add input Suffix, just like Prefix

**Comment by fega** [comment]
@Dogfalo this doesn't fit with the material design guidelines.

**Comment by ray007** [comment]
Need help here?
Any reason it's apparently not going into 1.0?

**Comment by ThomasGRIM** [comment]
Hi, is there anything left to do to help push this into the framework?
Thanks

**Pull request closed without merging**
