### PR TITLE
Restructure sass imports

### PR DESCRIPTION
**Pull request by tomscholz**
- Moved variables and normalize outside the components folder, since they just are not components.

### CODE REVIEW

**Comment by flexbox** [comment]
The actual [version of Normalize.css](https://necolas.github.io/normalize.css/) is 7.0.0

@tomscholz Do you think we can bump it on the same PR?

**Comment by DanielRuf** [comment]
Imo this should be integrated with npm and an import rule, not in our sass folder.

**Comment by flexbox** [comment]
Totally agreed!

But Maybe there are some custom rulez like in this file `js/date_picker/picker.date.js`

**Comment by DanielRuf** [comment]
Which rules do you mean?

**Comment by flexbox** [comment]
Just [watched the history](https://github.com/Dogfalo/materialize/commits/master/sass/components/_normalize.scss), And I think we can bump the version directly from the npm registry :rocket:

**Comment by tomscholz** [comment]
normalize has been updated to 7.0 in the v1 https://github.com/Dogfalo/materialize/commit/505ff791ad607b7b757945f68374f5a9db714081

**Pull request closed without merging**
