### PR TITLE
1422: Make materialize work with requireJS. Added hammerjs and jquery…

### PR DESCRIPTION
**Pull request by llhupp**
… to package.json. Set bin/materialize.js as main entry point.

#1422

### CODE REVIEW

**Comment by acburst** [comment]
You shouldn't edit bin/materialize.js directly because this is a generated, compiled file. You could probably find a better place to put it in global.js or something and then compile it into bin.

**Comment by llhupp** [comment]
I only changed `js/jquery.easing.1.3.js` and recompiled with `grunt monitor`... am I not supposed to commit the updated `bin/materialize.js`?

**Comment by acburst** [comment]
Oh, I see. Yeh, adding it to jquery.easing isn't the best idea because if we want to update it it will be lost. But looking at our compilation order, there really is no good place to put it atm. We'll have to think about this a little more I think.

**Comment by llhupp** [comment]
Ah... My mistake, I totally glossed over that that was a jQuery submodule... I thought it was just some hacked together implementation of jQuery. You're right, I shouldn't update that.. Maybe I should add that global.js like you were talking about..

**Comment by Dogfalo** [comment]
Closed since this was incorporated into #2381 unless I'm mistaken.

**Pull request closed without merging**
