### PR TITLE
Add global Materialize object to attach methods for export to Meteor app...

### PR DESCRIPTION
**Pull request by donaldaverill**
...s. Located in global.js.

Add the toast function to the Materialize global.
Export Materialize in the package.js file for Meteor apps.

### CODE REVIEW

**Comment by benjick** [comment]
+1

**Comment by spencercarli** [comment]
+1

**Comment by ls42** [comment]
:+1:

**Comment by johnschult** [comment]
I want this :+1:

**Comment by ForsakenHarmony** [comment]
Is this broken again?

**Pull request merged**
