### PR TITLE
Date- and Timepicker new layout according to md specs

### PR DESCRIPTION
**Pull request by philipraets**
@smileytechguy This is a replacement PR for PR #2732 

Reworked layout for datepicker to be like the specs including a landscape and portrait-layout
Added a Timepicker with the same layout
Added timepicker to docs

landscape:

portrait:

### CODE REVIEW

**Comment by DanielRuf** [comment]
@philipraets the green circle looks somehow skewed here: https://cloud.githubusercontent.com/assets/708011/12717707/e554502c-c8e9-11e5-90cb-1a15e9505a40.jpg

**Comment by philipraets** [comment]
@DanielRuf there will be some small css bugfixing to do like the circles and the spacing between the date and time text, I'll see if I can fix some tomorrow (these screenshots are from the previous PR, but the code is working). If this gets accepted, then maybe there are some people with better css-skills than me who can look at the code and fix some things or improve it.

**Comment by DanielRuf** [comment]
@philipraets quite much code. A small codepen with an example for the third screenshot would be helpful. I could test and fix this.

**Comment by tomscholz** [comment]
time-land
time-hor
date-land
date-hor

**Comment by smileytechguy** [comment]
Can we get some spacing between the time and AM/PM here: 
image ?
Also, maybe a way to customize the displayed date format?  Also, the datepicker on mobile looks like ovals

Finally, if we could get some waves would be cool too

**Comment by philipraets** [comment]
New screenshots (with css fix):
image

image

image

image

**Comment by smileytechguy** [comment]
Awesome!  Could you maybe make a codepen or something with this so I can test it?

**Comment by philipraets** [comment]
Here's a working codepen: https://codepen.io/anon/pen/evQxPy

**Comment by smileytechguy** [comment]
@philipraets In Google Chrome the pen seems to randomly refresh as soon as it renders

**Comment by philipraets** [comment]
these are the options for the timepicker:
```
$('.timepicker').pickatime({
    default: 'now', // Set default time
    fromnow: 0,       // set default time to * milliseconds from now (using with default = 'now')
    twelvehour: false, // Use AM/PM or 24-hour format
    donetext: 'OK', // text for done-button
    cleartext: 'Clear', // text for clear-button
    canceltext: 'Cancel', // Text for cancel-button
    autoclose: false, // automatic close timepicker
    ampmclickable: true, // make AM PM clickable
    aftershow: function(){} //Function for after opening timepicker
     
  });
```
The datepicker options are the same as before

There is a small waves-effect on the buttons, I've tried on the other clickable stuff, but waves-effect messes with the display property, so I have to find a workaround for it

to change the selects to materialize also gave me problems (I removed "browser-default" from them, but then there is a lot of work to get it right)

**Comment by smileytechguy** [comment]
alright, thanks . It looks great so far!

**Comment by tomscholz** [comment]
@smileytechguy @philipraets I think this could be achieved by using the variables $primary-color and $secondary-color

**Comment by philipraets** [comment]
You can change the colors using the variables or like I did in my app (because we a different color scheme for different modules) add some css rules like these to an extra css-file:
```
.picker__holder.green-picker .picker__date-display,
.picker__holder.green-picker .picker__day--selected,
.picker__holder.green-picker .picker__day--selected:hover,
.picker__holder.green-picker .picker--focused .picker__day--selected {
background: #4caf50 none repeat scroll 0 0;
}
```

**Comment by philipraets** [comment]
Screenshot timepicker 24-hour format:
image

image

**Comment by rogeriocorrea** [comment]
I think that a have found a little bug. When we have a time picker with a input pre-initialized with AM, for example, "08:00AM", the AM part is ignored when the picker is open and changed to PM when confirmed.
Here is a codepen reproducing the issue: https://codepen.io/rogeriocorrea/pen/QpoKrB

**Comment by philipraets** [comment]
@rogeriocorrea: I've just commited a fix for this. It should have the correct AM PM value now.

**Comment by NonameSLdev** [comment]
@philipraets It seems really neat. Here's an idea: how about a js option to set pickers vertical/horizontal programmatically (where it defaults according to the screen orientation)? :)

**Comment by Dogfalo** [comment]
Just wanted to say, looks awesome @philipraets. Will have a thorough look at this next week.

**Comment by jeroenqui** [comment]
Looks fantastic! Hope this gets approved

**Comment by zerobig** [comment]
How about date and time in one dialog?
Something like http://simeonc.github.io/md-date-time/

**Comment by kapalkat** [comment]
Stupid question but I am new to Git Hub:)
How to make the timepicker working in my project using the branch which contains it?
I am downloading following branch https://github.com/philipraets/materialize/archive/abe3466d3f5734ca33d68c567c766e91de91663c.zip
and using materialize.css and materialize.js from /dist but this is not working...

**Comment by philipraets** [comment]
@kapalkat

you create an input field like this:

``
<input type="date" class="timepicker">
``
and then initialize the timepicker with the following code:
```

  $('.timepicker').pickatime({
    default: 'now', // Set default time
    fromnow: 0,       // set default time to * milliseconds from now (using with default = 'now')
    twelvehour: false, // Use AM/PM or 24-hour format
    donetext: 'OK', // text for done-button
    cleartext: 'Clear', // text for clear-button
    canceltext: 'Cancel', // Text for cancel-button
    autoclose: false, // automatic close timepicker
    ampmclickable: true, // make AM PM clickable
    aftershow: function(){} //Function for after opening timepicker  
  });
```

**Comment by kapalkat** [comment]
@philipraets 

Thanks for the comment. Yap exactly that's what I'am doing:
<input name="time" value="07:00" class="timepicker" id="id_time" type="date">

value="07:00" is my default btw.

**Comment by philipraets** [comment]
@kapalkat

I didn't think about it, but it's because I don't push those files to github, so the timepicker isn't in those files.

You can compile them with grunt, or you can use these:
[materialize.css](https://m.boma.eu/materialize/css/materialize.css)
[materialize.js](https://m.boma.eu/materialize/js/materialize.js)

These are the compiled files for this branch

**Comment by kapalkat** [comment]
Jiiiz...:)
Thanks a lot! It's working right now.
I had one more issue and probably this was the reason at the first place why it was not working.
I was using jquery 3.2.1
I have changed it to version: 2.1.1 and now all is working fine with the files you have attached.

BTW:
The timepicker is GREAT! I really appreciate your work!

**Comment by Dogfalo** [comment]
Cleaning up some code and modifying style so it more closely matches the spec. Currently debating on whether to handle the color inversion on the hour/minute text over the clock handle

**Comment by smileytechguy** [comment]
@Dogfalo I say let the user handle it, most other components require the user to manage stuff like that

**Comment by Dogfalo** [comment]
Finally finished up last batch of changes. Thanks everyone for the work you put in and for your patience.

Please give it a try and file bug reports :smile:

**Comment by SamuraiT** [comment]
Hello, this pull request is merged and seems like `datetime` function is made.
But whever I googled, I cannot find any document or implementation to make the datetime function which by once you will input the date and the time. 

could you tell me how to use/implement datetime function using materiaize? 
thank you in advance
@Dogfalo , @philipraets

**Pull request merged**
