### PR TITLE
remove old drag-target

### PR DESCRIPTION
**Pull request by zhaoyao91**
remove old drag-target to prevent a lot of drat-target after re-init several times.

### CODE REVIEW

**Comment by zhaoyao91** [comment]
remove old drag-target to prevent a lot of drat-target after re-init several times.

**Comment by tomscholz** [comment]
@DanielRuf This looks good to me, but @zhaoyao91 Is this an issue that happens a lot?

**Comment by DanielRuf** [comment]
Could be simplified. We could check with `.lenth` if the element already exists and append it if not.

But this here works too and also looks good to me.

**Comment by acburst** [comment]
This has been taken care of in the sidenav rewrite for v1

**Comment by DanielRuf** [comment]
@acburst can you link the commit which fixes it?

**Pull request closed without merging**
