### PR TITLE
Add a .hide class to hide an element

### PR DESCRIPTION
**Pull request by brandonjmckay**
I wanted a class to toggle on, and off to be able to hide elements in css.

I think this is a decent thing for the framework to handle; Materialize already has a lot of `.hide-on-med-and-up` style classes.

I find I use this a lot, and usually get this function from Bootstrap. I use this when I want Ember to render a template, but not display it yet.

### CODE REVIEW

**Comment by Dogfalo** [comment]
Thanks for this, but I had to make the change manually as there were too many other changes in your commit, and the wrong documentation file was edited.

See 296a3263b7c3d40ae221398414e911acd3200eb1

**Comment by brandonjmckay** [comment]
I think the other changes were partly the way that grunt compiled my css. Are there any special configs to be aware of?

**Comment by Dogfalo** [comment]
If you used our grunt script, it should be exactly the same format.

**Comment by brandonjmckay** [comment]
grunt script? Not sure which that was. I followed online docs on how to install grunt, then ran `grunt watcher` or something.

This was the first I've used grunt. May have botched it.

**Comment by brandonjmckay** [comment]
Good to know it should look the same, I'll keep that in mind next time.

**Pull request closed without merging**
