### PR TITLE
Fixed https://github.com/Dogfalo/materialize/issues/5257

### LINKED ISSUE #5257: characterCounter() doesn't work after dynamically adding
Hi All
Question is about dinamically appending characterCounter part.
Yes I know that I should initialize after dynamically adding, but it doesn't work 
my input parts adding dynamically like this 

```
var clone = SMTHING.cloneNode(true);
clone.getElementsByClassName('sm-class')[0].innerHTML = 'smth';
.
.
SOMETHINGELSE.appendChild(clone);
```

good, but 
before appending `$(clone).find('#textarea1').characterCounter();`
or after appending `$('#textarea1').characterCounter();`
it doesn't work 
it works correctly when I doesn't add dynamically,
Also I can see the added span.character-counter  , but js part (on focus or on blur) doesn't work , 

thanks in advance

### PR DESCRIPTION
**Pull request by developeranirudhprabhu**
Fixed: https://github.com/Dogfalo/materialize/issues/5257

Changes:
* Removed the counterElement length check
* Added off binds to the element

This changes will allow dynamic initialisation of charactercounter plugin

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by acburst** [comment]
Have you tested this issue in v1? We are no longer looking to merge changes from older versions.

**Comment by developeranirudhprabhu** [comment]
So only v1 branches are being considered? I will check the codebase there then.

Sent from my Huawei Mobile

-------- Original Message --------
Subject: Re: [Dogfalo/materialize] Fixed https://github.com/Dogfalo/materialize/issues/5257 (#5340)
From: Alan Chang
To: Dogfalo/materialize
CC: Anirudh Prabhu ,Author


Have you tested this issue in v1? We are no longer looking to merge changes from older versions.

**Comment by developeranirudhprabhu** [comment]
I will check the v1 branch tonight and confirm. In case this issue exist then how should i proceed?

**Comment by acburst** [comment]
You can open a new PR / Issue

**Comment by developeranirudhprabhu** [comment]
The problem is different in this case. The dynamic initialisation takes place however the counter gives all wrong values. Need to confirm what exactly is wrong. Attaching the screenshot. Will look into it
screen shot 2017-11-15 at 10 33 16 am

**Comment by developeranirudhprabhu** [comment]
@acburst You can reject the old PR. Cause v1 has all together different code and a different issues

**Comment by developeranirudhprabhu** [comment]
@acburst This is to confirm the issue is resolved in v1 branch. You may close this issue as well as the PR. Thanks

**Pull request closed without merging**
