### PR TITLE
Enhancement to add a date time picker

### PR DESCRIPTION
**Pull request by rthomson83**
I needed a datetime picker so decided to port one myself for using with an angularjs project and thought I would share it. 
I ended up using bootstrap-material-datetimepicker.js over at https://github.com/T00rk/bootstrap-material-datetimepicker

Not sure if this is the way you want to go and there's some enhancements like adding a today button etc that would be worthwhile.

image

### CODE REVIEW

**Comment by rthomson83** [comment]
Should satisfy issue #473.

**Comment by xxryan1234** [comment]
+1

**Comment by cDima** [comment]
Wow, thanks @rthomson83 just what I needed.

**Comment by rthomson83** [comment]
Glad it helped @cDima!

**Comment by tomscholz** [comment]
See: https://github.com/Dogfalo/materialize/pull/4445

**Pull request closed without merging**
