### PR TITLE
Remove roboto from source

### PR DESCRIPTION
**Pull request by tomscholz**
## Proposed changes
Having the Roboto font inside the project is making it difficult to use the materialize-css npm package and it is making the repo unnecessary big. About ~1.5mb. Adding a guide how to obtain the font from a CDN or how to include it via @font-face would be the way to go.
Fixes: #2217
- [x] Add instructions (jade)
- [x] Remove `fonts/` & `dist/fonts`
- [x] Edit Gruntfile.js
- [x] Modify package.js
- [x] Edit templates
- [x] Remove [_roboto.scss](https://github.com/Dogfalo/materialize/blob/c0d5a9f9b228841ac4db9a1532df11a2a4adbefd/sass/components/_roboto.scss) and modify [variables](https://github.com/Dogfalo/materialize/blob/master/sass/components/_variables.scss#L147)
- [x] Remove from bower.json

Closes https://github.com/Dogfalo/materialize/issues/4797

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tomscholz** [comment]
@DanielRuf any idea why the test fails? I can't spot any json error inside the package.json :/

**Comment by DanielRuf** [comment]
`Trailing comma in object at 24:3`
https://github.com/tomscholz/materialize/blob/285c10152a75dafa9153b8db9a87f055aa979927/package.json#L23

**Comment by DanielRuf** [comment]
See the actual error when linting with https://jsonlint.com

```
Error: Parse error on line 23:
...jquery": "^3.2.1",	},	"engine": "node 
----------------------^
Expecting 'STRING', got '}'
```

**Comment by tomscholz** [comment]
@DanielRuf thx

**Comment by IAMtheIAM** [comment]
This breaks building with webpack, why do this?

```
ERROR in ./node_modules/materialize-css/sass/materialize.scss
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '../fonts/roboto/Roboto-Thin.woff2' in 'C:\Source\frontend\node_modules\materialize-css\sass'
```

**Comment by DanielRuf** [comment]
@IAMtheIAM did you test https://github.com/tomscholz/materialize/tree/remove-roboto?

**Comment by tomscholz** [comment]
Any updates on this?
@Dogfalo @acburst

**Comment by tomscholz** [comment]
I guess a merge squash would make sense here...

**Comment by IAMtheIAM** [comment]
@DanielRuf I did test https://github.com/tomscholz/materialize/tree/remove-roboto and it compiles successfully. Will this be merged to master soon?

**Comment by tomscholz** [comment]
I dont know

**Comment by peabnuts123** [comment]
This looks good… what's holding it back?

**Comment by tomscholz** [comment]
I don't know

**Comment by peabnuts123** [comment]
Oh, I see… this repo has 150 open PRs… I guess they don't monitor their contributions much.

**Comment by IAMtheIAM** [comment]
@peabnuts123 They do monitor it, but they have a lot to review when its comes to PRs, Issues, and their own code enhancements. They'll get to it, its in the [next release milestone](https://github.com/Dogfalo/materialize/milestone/6).

**Comment by tomscholz** [comment]
@IAMtheIAM Haha ^^ I originally created that milestone. My guess is that this will come with one of the next releases, but I can't say for sure.

**Comment by tomscholz** [comment]
@Dogfalo Would this get merged, when I make the PR against the v1-dev branch?

**Comment by Dogfalo** [comment]
@tomscholz Yes I will merge it if it is made on the v1-dev branch

**Comment by tomscholz** [comment]
Got it

**Comment by peabnuts123** [comment]
Please link the new PR here when it is made

**Comment by Dogfalo** [comment]
@tomscholz Maybe you have been busy, but I didn't notice a PR. No problem though, I will go through now and remove the files.

**Comment by tomscholz** [comment]
@Dogfalo Thats cool. Yes I have been very busy lately, sorry for not posting any updates

**Pull request closed without merging**
