### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by 1xxxx**
English - Chinese

### CODE REVIEW

**Comment by makzimko** [comment]
Are u kidding? English comment to Chinese? You want to make project not supportable or what?

**Comment by 1xxxx** [comment]
@makzimko 1、You misunderstood, sometimes machine translation language is not accurate.
2、SO, I carefully opened the dusty many years of high school English dictionary to answer your "questions"

**Comment by makzimko** [comment]
@1xxxx documentation on Chinese is a pretty bad idea. I know that more than one billion people know Chinese, but believe me that English is more in all the world. So with documentation in Chinese other world can't support project

**Comment by 1xxxx** [comment]
Compile the document ≠ code, you understand?
Just want to compile, one billion people also do not understand the English language programmers, such as me.

**Comment by 1xxxx** [comment]
@makzimko Compile the document ≠ code, you understand?

**Comment by acburst** [comment]
Not really sure I understand, but i'm closing this

**Pull request closed without merging**
