### PR TITLE
Adding initial dark theme changes

### PR DESCRIPTION
**Pull request by Ecksters**
Based on my issue #1323, I started adding a dark theme to the scss files, using a the `$dark-theme` variable, which is set to false by default, turning it to true changes the theme to dark.

Not certain if this implementation method is ideal, but I suppose I just want to try something out for it, and this at least can show what changes would need to be made to create a dark theme.

### CODE REVIEW

**Comment by DaEckster** [comment]
image

Here's just a look at what I'm thinking of.

**Comment by HenriBeck** [comment]
Looks great @DaEckster

**Comment by zot24** [comment]
:+1:

**Comment by carloscarcamo** [comment]
:+1:

**Comment by acburst** [comment]
I think instead of making this an inherent part of the framework, you can make your own theme with these dark color values replaced in the variables.scss file. I don't think we need more color variables when really this is just a color theme.

**Comment by truenorth** [comment]
:+1:

**Comment by Neotrixsx** [comment]
:+1:

**Comment by DaEckster** [comment]
@acburst Yeah, that was something I was a bit afraid of, I don't want to clutter up the main scss code with theme, the only reason I thought it would possibly be okay is because Material design specifically shows dark and light themes, while adding colors appears to be intended for simply accenting, not as a main color scheme. This is actually why I haven't continued making more commits, since I assumed this wasn't an ideal implementation strategy in the long-run.

Would love to see an example of implementing a full theme redo, because the current SCSS makes a lot of assumptions that the background will be white, so some major changes would need to be made for the variables.scss file to support full theme changes.

**Comment by acburst** [comment]
I was thinking about this, but if you wanted to make a template of sorts using a nice dark color scheme, we can look into adding it into the templates section of our documentation.

**Comment by Ecksters** [comment]
Well, the main dilemma with that is that keeping that template up-to-date with future changes would be extremely difficult, since various of the scss need to be modified to achieve the dark look. Like I said, the current implementation assumes a light-colored background in many locations in the code. I think that would need to be corrected before it'd be worth putting much effort into a full dark theme. :tired_face:

**Comment by ProfNandaa** [comment]
@Ecksters  

The theme looks great!

A quick one, as per the conversation above, should this PR be closed now?

**Comment by ManuZiD** [comment]
Awesome work :+1:

**Comment by Ecksters** [comment]
Yes, it should probably be closed as it requires major changes to the framework to add dark theme support.

**Pull request closed without merging**
