### PR TITLE
Incorrect input type in form example.

### PR DESCRIPTION
**Pull request by labnol**
Input type should be set to text for time picker example.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Any reason why? Date is used for datetime.

**Comment by DanielRuf** [comment]
https://github.com/Dogfalo/materialize/pull/4882#issuecomment-310851766

I think text is not the right type, might need some refactoring imho (the datepicker uses date).

**Comment by tomscholz** [comment]
Why not choose `type="time"` over `type="text"` ?

**Comment by Dogfalo** [comment]
As of now text is the correct type, time will add other UI elements which are not easily overridden

**Pull request merged**
