### PR TITLE
the labels the same color in the checked state

### PR DESCRIPTION
**Pull request by refactorsheep**
I think  the design of the labels for the radio button and check boxes could be improved.
I made the labels the same color in the checked state.
Before I create a fork, please tell me what you think.
checkbox_radio

### CODE REVIEW

**Comment by uok** [comment]
good improvment!

**Comment by dali99** [comment]
:+1:

**Comment by refactorsheep** [comment]
thanks:D

**Comment by mmarj** [comment]
:+1:

**Comment by tomscholz** [comment]
I'm going to close this pr because it's very old and any new discussion should probably happen on a new pr with a more specific title!

**Pull request closed without merging**
