### PR TITLE
Adding open/close callbacks to sideNav options. fixes #2830

### LINKED ISSUE #2830: listen to opening/closing event on sideNav
hello, 

how can i check if my mobile is "opened" or "closed"? i want to switch the hamburger icon to a close icon if the nav is opened... and i couldn't find out how.

### PR DESCRIPTION
**Pull request by DonHartman**
Adds open/close callbacks to sideNav options. fixes #2830

### CODE REVIEW

**Comment by smileytechguy** [comment]
lets get this added!

**Comment by ferchoman09** [comment]
We can use that on latest release?

**Comment by DonHartman** [comment]
@ferchoman09 
I've been keeping it up to date, but it's not merged yet. 

If @Dogfalo or @acburst decide to accept the pull request, then you can.

**Comment by ferchoman09** [comment]
@DonHartman thanks for your response.
I'll be waiting for that. I need that for my AngularJS project. :-(

**Comment by cicoph** [comment]
ehii merge this fix please

**Comment by cicoph** [comment]
@DonHartman @Dogfalo @acburst ehi pull this request please!!!

**Comment by guicara** [comment]
Hello,

This feature should ne added to the core. It is really important to listen on this events. Cloud you please review this pull request?

Thanks

**Pull request merged**
