### PR TITLE
datepicker font size now displays month correctly

### PR DESCRIPTION
**Pull request by gilbertoayala12**
## Proposed changes
Added changes to datepicker specifically when selecting a month because the size of the text was to big and now it shows with a correct size

## Pre-fix image
Screen Shot 2019-11-26 at 12 25 07 PM

## Fixed 
Screen Shot 2019-11-26 at 12 26 37 PM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Wouldn't this fail with a longer string too?

**Comment by gilbertoayala12** [comment]
> Wouldn't this fail with a longer string too?

Yes. I tested it with `september` since it's the longest string in the calendar and it works correctly.

**Comment by DanielRuf** [comment]
And other languages? ;-)

**Comment by gilbertoayala12** [comment]
You're right and I added a text-overflow property just in case anything like that happens 😅

**Pull request closed without merging**
