### PR TITLE
Fix navbar search who wasn't taking full height in all browser

### PR DESCRIPTION
**Pull request by NitroBAY**
Hello, it's a fix to the bug reported by #2971 and #2903. I tested it on IE 11

### CODE REVIEW

**Comment by Josepdal** [comment]
Hey, i tried this, but is necessary to put the form height up to 100% too.

Check it here: http://taligram.org/en/channels so many thanks :smiley:

**Comment by NitroBAY** [comment]
You welcome, as I didn't use form in my search I didn't saw that, I'll commit soon then :D

**Comment by NitroBAY** [comment]
Actually even with form tag surrounding search navbar as proposed by doc it's good for me in IE 11, but I can reproduce the issue of your website as you use search from navbar in a non convential way by removing height 100% from form thus I'll include your modify

**Comment by Josepdal** [comment]
Nice job :) :+1:

**Comment by acburst** [comment]
Thanks!

**Pull request merged**
