### PR TITLE
Correcting the positioning of the dropdown component of the pop-up list in the modal window.

### PR DESCRIPTION
**Pull request by gewisser**
## Proposed changes
If dropdown is in the modal window, it automatically calculates its location. Issue: #4618

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Dogfalo** [comment]
This should be fixed by the new dropdown code in v1-dev. Please test it

**Comment by gewisser** [comment]
In v1-dev, this is fixed. But I very much ask, please, also apply this fix in the current version.

**Comment by Dogfalo** [comment]
If you already have a fix for it, then you can use it in your project.

**Comment by tomscholz** [comment]
@Dogfalo I agree with @gewisser, a new release would make sense. 0.100.3

**Pull request closed without merging**
