### PR TITLE
Feature/fixed navbar jumps

### PR DESCRIPTION
**Pull request by ManuZiD**
Reference to the following issue: [4635](https://github.com/Dogfalo/materialize/issues/4635)

Now it's possible to prevent this issue with the option `hideScrollBar`. The default value of this option is true. To prevent these jumps you have to set the value to false.

Default behaviour: https://codepen.io/anon/pen/GmEmgQ

Behaviour without jumps: https://codepen.io/anon/pen/XRYZMp

### CODE REVIEW

**Comment by tomscholz** [comment]
Are you running on windows?

**Comment by ManuZiD** [comment]
On work. Why do you ask?

**Comment by tomscholz** [comment]
Cuz I wasn't able to reproduce it on a mac in chrome,safari or firefox. Was just confused

**Comment by ManuZiD** [comment]
Yes, that's a windows exclusive bug :)

**Comment by Dogfalo** [comment]
Added an option in sidenav and modal in a9a87f4f9cec5e7412a097a132c64cb8ff671663

**Pull request closed without merging**
