### PR TITLE
[BUGFIX] Fixed material_select function to set clicked item as active (Issue #1400)

### PR DESCRIPTION
**Pull request by RakanNimer**
The _active_ class was being set on list items in a select on select _focus_ event instead of the li _click_ event. 
I adapted the logic in forms.js for this.
This code does not change anything in the UI, it is for programatically retrieving the selected list item.

### CODE REVIEW

**Comment by Sajgoniarz** [comment]
Now, just need to w8 :) Thanks, a lot.

**Comment by Dogfalo** [comment]
This probably breaks keyboard support

**Comment by RakanNimer** [comment]
Hey @Dogfalo ! 
Thanks for your work on materialize it's great ! 
You were right the fix broke keyboard support when no option is selected.
Fixed that by setting the first element's class to active keeping it consistent.
Cheers !

**Comment by acburst** [comment]
Should be fixed on latest release

**Pull request closed without merging**
