### PR TITLE
 Fixed the url

### PR DESCRIPTION
**Pull request by Kennection**
## Proposed changes

It redirected me to the old one. I just add "next." to it
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Dogfalo** [comment]
Thanks!

**Comment by Kennection** [comment]
You're welcome

**Comment by Kennection** [comment]
I think I've made a wrong choice. I should've read again the contibuting.md. Is this ok?

**Comment by Kennection** [comment]
@Dogfalo

**Comment by Dogfalo** [comment]
Are you referring to deleting the branch? It's fine to delete it after it's merged in.

**Comment by Kennection** [comment]
It is said that if when I'm contributing to Materialize's documentation, you should edit the documentation source files in the /materialize/jade/page-contents/ directory of the master branch. Hmmm...nevermind I didn't contribute on documentation, I've just update an URL

**Pull request merged**
