### PR TITLE
Move template binaries to the releases section of github

### PR DESCRIPTION
**Pull request by tomscholz**
## Proposed changes

- Unnecessary junk, that does not have to be in the repository
- The url gets changed automatically with the `grunt release --oldver=vx.xx.x --newver=vx.xx.x` task

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hm, I just see the top banner code which is added by `grunt release`. I see no code to update the URL or did I oversee something?

**Comment by tomscholz** [comment]
See https://github.com/Dogfalo/materialize/blob/master/Gruntfile.js#L495

**Comment by DanielRuf** [comment]
I guess you probably mean `grunt release --oldver=vx.xx.x --newver=vx.xx.x`.

**Comment by tomscholz** [comment]
Same procedure as here https://github.com/Dogfalo/materialize/pull/4832

**Comment by DanielRuf** [comment]
Well, without these options there is probably nothing replaced afaik.

**Comment by tomscholz** [comment]
Yes, but I think that is okay since we would only use it for production.

**Comment by DanielRuf** [comment]
Right. Just wanted to note the command that you and the others would need for this =)

**Pull request closed without merging**
