### PR TITLE
Remove font files to stop bower throwing warnings

### PR DESCRIPTION
**Pull request by MarleyPlant**
## Proposed changes
When installing the package via bower errors are being thrown. This commit fixes this issue by removing the font files from the main property in bower.json

## Screenshots (if appropriate) or codepen:

screenshot
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DanielRuf** [comment]
See https://github.com/Dogfalo/materialize/pull/4798

**Comment by MarleyPlant** [comment]
Thanks for the quick response @DanielRuf I have read through that thread and from what I can gather it seems they are suggesting completely removing the font files from the repo.

where I am suggesting removing the font files from the main bower.json file to stop bower throwing errors.

is there no way of  bundling the font files into the css file the same way that they do with the Font-Awesome project?

**Comment by tomscholz** [comment]
> is there no way of bundling the font files into the css file the same way that they do with the Font-Awesome project?

What do you mean?

**Comment by MarleyPlant** [comment]
in the Font-Awesome project the error is not thrown and they are also using font files? looking at their bower.json they aren't referencing any font files in the main files property.

Just trying to see if there is a better alternative to just leaving the warning there

**Comment by DanielRuf** [comment]
People shall install the Roboto font file fro the Google CDN or install the with npm / yarn / bower / composer using font-face. The PR by @tomscholz makes this PR obsolete.

A warning is not an error in this case. It is currently just an antipattern to have the font files in the main field.

**Comment by DanielRuf** [comment]
The bower file of the FontAwesome project was last updated in 2015. Bower is dead

**Pull request closed without merging**
