### PR TITLE
Required Field Validation

### PR DESCRIPTION
**Pull request by acebruin**
- Fixed bug to catch required fields validation

### CODE REVIEW

**Comment by jtuberville** [comment]
This corrects an issue with the html5 "required" attribute not being recognized by the "validate" class handling logic.

**Comment by Dogfalo** [comment]
I'm not entirely sure whether we should be tying the validation style to the `validate` attribute. Maybe @acburst can chime in as well on what he thinks.

I think this change might be good although it will definitely require some documentation changes if it goes through.

**Comment by scote** [comment]
@acburst may you check this pull request? It would be nice to have this feature in next version.

**Comment by tomscholz** [comment]
@acburst @Dogfalo Can you check on this please?

**Comment by Dogfalo** [comment]
Merged similar PR here: #4883

**Comment by acebruin** [comment]
#4883 doesn't have line 61 fix for the selector

**Pull request closed without merging**
