### PR TITLE
Small typo

### PR DESCRIPTION
**Pull request by rohitrango**

### CODE REVIEW

**Comment by komali2** [comment]
Probably better to use "as" rather than "and."

**Comment by rohitrango** [comment]
Sorry for my english :laughing:

**Comment by rohitrango** [comment]
I think this should be able to be merged now! 
Please review.

**Comment by Dogfalo** [comment]
Couldn't merge this because you didn't edit the jade file, but I made this change in 326b8736fa35edcca68e13196943a3d956d30bdd

**Pull request closed without merging**
