### PR TITLE
Updated changelogs and readme

### PR DESCRIPTION
**Pull request by tomscholz**
- Added new releases to CHANGELOG.md
- Removed full changelog and pointed to the CHANGELOG.md instead
- Added better alt tags to images
- Update ISSUE_TEMPLATE.md
- Restructured CONTRIBUTING and added more information about Pull requests
- Added a little quick start guide and information about how to compile files
- Added the `autocompleteOptions` change in 0.98.2

### CODE REVIEW

**Comment by DanielRuf** [comment]
Don't forget the `autocompleteOptions` change in 0.98.2 ;-)

**Comment by tomscholz** [comment]
@DanielRuf There you go :)

**Comment by tomscholz** [comment]
@fega What do you think? Are you ok with merging this?

**Comment by fega** [comment]
👍

**Comment by tomscholz** [comment]
cc @acburst

**Pull request merged**
