### PR TITLE
Improved autocomplete

### PR DESCRIPTION
**Pull request by jonathanarodr**
Added improve in autocomplete to use attributes in their ID's, resolved issue [#4086](https://github.com/Dogfalo/materialize/issues/4086).
Added **scrollLength** attribute to allow you to set the limit of items to be displayed before the scroll.

### CODE REVIEW

**Comment by djensen47** [comment]
Thanks for doing this! Hopfully @Dogfalo will accept this PR.

**Comment by jonathanarodr** [comment]
Thanks @djensen47 !

**Comment by djensen47** [comment]
cc: @Dogfalo @acburst @ajmark @tomscholz @klouie93 @kmmbvnr

What's the hold up on accepting this pull request. It passes the tests, it seems like it is ready to go.

**Comment by tomscholz** [comment]
I guess we need some more new documentation about it

**Comment by tomscholz** [comment]
Related: https://github.com/Dogfalo/materialize/pull/3954

**Comment by djensen47** [comment]
@tomscholz It appears that an update to the documentation was included in the PR. Is there something specific that is missing? Would it be possible to accept this PR and add a new issue to expand on the existing documentation?

**Comment by jonathanarodr** [comment]
@tomscholz there is an update documentation on improving the autocomplete in my PR, I believe it will help in its use

**Comment by storm1er** [comment]
Takecare of breaking change :/

**Comment by Maqsyo** [comment]
I can't see this in the code, but support this code the old way?
Maybe this would good with a console.warn('deprecated')
And please update the documentation, so @tomscholz can merge it without any extra work ^^

**Comment by crobinson42** [comment]
What's holding this PR up?

**Comment by Dogfalo** [comment]
We're doing refactoring and rewriting for our v1.0.0 release. So when the time comes to autocomplete, we'll be looking to possibly merge this, but we won't be merging this in the the current pre-v1 releases

**Comment by maxkaplan** [comment]
+1 👍

**Comment by iv-mexx** [comment]
@Dogfalo since 1.0 has been released, has the time come now to look into this again?

**Pull request closed without merging**
