### PR TITLE
Fix conflict select with datepicker select

### PR DESCRIPTION
**Pull request by danilobrinu**
## Proposed changes

This fix a error when use datepicker.

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [ ] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tomscholz** [comment]
Please explain the changes you made in depth otherwise we have to close this pull request

**Comment by danilobrinu** [comment]
@tomscholz i find a issue when use datepicker (.inpufield select) affect to datepicker and set height to 0. I restrict selector to (.input-field > select).

**Comment by tomscholz** [comment]
It seems that you haven't read our [contributing guidelines](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md#pull-requests). 
See:
> Please ask first before working on any significant pull request, otherwise you risk spending a lot of time working on something that the project's developers might not want to merge into the project.

Also make sure to read the section about [bug reports](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md#bug-reports) and create a [reduced test case](https://css-tricks.com/reduced-test-cases/) using **our** [Codepen template](http://codepen.io/Dogfalo/pen/xbzPQV).

**Comment by danilobrinu** [comment]
@tomscholz okay.

**Comment by Dogfalo** [comment]
Added already

**Pull request closed without merging**
