### PR TITLE
Feature request: Autocomplete

### PR DESCRIPTION
**Pull request by SuperDJ**
As seen here: https://www.google.com/design/spec/components/text-fields.html#text-fields-auto-complete-text-field a  autocomplete could have icons.

I came up with the following:

Still todo:

- Fix a bug when comparing strings;
- Test with other browsers (tested in: Chrome, FireFox working same in both);
- Test with different types of input (text tested);
- Add support to highlight matching characters;
- Add different styling for highlight matching characters

### CODE REVIEW

**Comment by Verkalets** [comment]
@SuperDJ ah, this is really cool feature. Waiting for merge.

**Comment by Fessalian** [comment]
+1

**Comment by beforeadream** [comment]
+1

**Comment by carusogabriel** [comment]
Amazing one
`+1`

**Comment by yhaskell** [comment]
@SuperDJ could you please update this so it would be automerged and hopefully seen soon?)

**Comment by SuperDJ** [comment]
**UPDATE**

Sorry for being inactive for a while but I have fixed a couple of bugs. I'm currently working on highlighting matching text. When all is done I'll create a new PR because I have deleted this one. The new PR has a lot less code.

**Comment by SuperDJ** [comment]
Created new [PR](https://github.com/Dogfalo/materialize/pull/2669])

**Pull request closed without merging**
