### PR TITLE
Fixed tap target position with scrollbars

### PR DESCRIPTION
**Pull request by inventti-leonardo**
I have been tested the tap target feature and got this issue.

### CODE REVIEW

**Comment by acburst** [comment]
Can you describe the issue more or help me reproduce the problem?

**Comment by inventti-leonardo** [comment]
I saved a codepen using files from git (bin/materialize.css, bin/materialize.js and feature-discovery.html):
http://codepen.io/anon/pen/GrLwgW

To reproduce, click on "open tap target" and will show a target misaligned, because of scroll

**Comment by inventti-leonardo** [comment]
I worked to fix both horizontal and vertical scroll when tap target is showed.
Can you review/refactor/merge @acburst ?

**Comment by acburst** [comment]
Thanks! this works well

**Comment by adick** [comment]
It got a lot better with the above [commits](https://github.com/Dogfalo/materialize/pull/4247/commits), but there was still an issue on mobile devices. The height of the visible/invisible address bar causes the windowHeight to be off. 

To fix this, change line 98 to: 

```
// var windowHeight = $(window).height();
var windowHeight = window.innerHeight ? window.innerHeight : $(window).height();
```

**Pull request merged**
