### PR TITLE
Feature #548 - allow select component to be controlled by keyboard

### PR DESCRIPTION
**Pull request by robinbortlik**
- refactored dropdown component
- add open and close listeners to dropdown component
- refactored select component (replace span by input)
- add keypress binding and logic to select

### CODE REVIEW

**Comment by Dogfalo** [comment]
I took a look at this, it looks very good. Just wondering why the animation style has been changed for the select dropdown?

**Comment by robinbortlik** [comment]
Ohh, really? I did not noticed any change in animation. Let me know, if it will need some fixes.

**Comment by robinbortlik** [comment]
Or do you mean the css style changes? That I had to replace arrow with icon? It is because, it is not possible to use :after selector with input.

**Comment by Dogfalo** [comment]
Take a look at http://materializecss.com/forms.html and click on the select dropdown. Then if you click the one after the change it has a different effect.

**Comment by robinbortlik** [comment]
Yes, you are right. I think it is issue with the scrollTo function. hhttps://github.com/Dogfalo/materialize/pull/582/files#diff-338f03716a63d52eee0f79b4510d617cR245

When you open the select, then the dropdown should be on the position of selected option. 
Maybe we can postpone this behaviour with setTimeout. So it will "maybe" stop break the initial animation. I will look on it on tomorrow evening.

**Comment by Dogfalo** [comment]
Great, looking forward to seeing it. Thanks for taking the time to add this
functionality for us!

On Mon, Feb 2, 2015 at 4:15 PM, Robin Bortlík <notifications@github.com>
wrote:

> Yes, you are right. I think it is issue with the scrollTo function.
> hhttps://
> github.com/Dogfalo/materialize/pull/582/files#diff-338f03716a63d52eee0f79b4510d617cR245
>
> When you open the select, then the dropdown should be on the position of
> selected option.
> Maybe we can postpone this behaviour with setTimeout. So it will "maybe"
> stop break the initial animation. I will look on it on tomorrow evening.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/pull/582#issuecomment-72539389>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by robinbortlik** [comment]
Ok, fixed. Can you test it now? :)

**Comment by Dogfalo** [comment]
Looks like it is working now. I merged it in. Thanks again for your help :)

**Comment by NewBo1234** [comment]
Please....what was the fix?  This is something I desperately need.  Where can I look at the code?

**Comment by robinbortlik** [comment]
Hi @NewBo1234 , 

this is a commit which added a functionality: https://github.com/Dogfalo/materialize/pull/582/commits/ec69063ac60bda0050f88e7c2ed9aea97c56988d
Can you access the page?

Regarding to your second issue, I'm afraid, that you will have to investigate by yourself. I remember that times when I was working on this library, I had to pull it locally, update a code as I needed and then compile it for myself.

**Pull request closed without merging**
