### PR TITLE
Modal open on button trigger

### PR DESCRIPTION
**Pull request by martinglover**
Button tag can be used to open a modal by setting the `data-target` to the Modal ID, documentation updated

### CODE REVIEW

**Comment by luanmuniz** [comment]
:+1:

**Comment by Dogfalo** [comment]
Instead of editing `modals.html`, please edit `modals-content.html`, other than that, looks good!

**Comment by martinglover** [comment]
Was unaware of the jade script, that's updated now

**Comment by Dogfalo** [comment]
Merged. Good stuff.

**Pull request merged**
