### PR TITLE
fix issue #3450 Background page is scrolling in Modal popup on mobile

### PR DESCRIPTION
**Pull request by haojia321**
This is to fix issue #3450 
https://github.com/Dogfalo/materialize/issues/3450

Page will still scrollable after open modal on mobile device.
Solution, Set your body width: 100%; and position: fixed; when modal is displayed.
Only set those 2 styles when modal is showed.

### CODE REVIEW

**Comment by haojia321** [comment]
https://github.com/Dogfalo/materialize/issues/3450

**Comment by haojia321** [comment]
#3450

**Comment by haojia321** [comment]
#3450

**Comment by haojia321** [comment]
Should I create a new PR? Sorry I'm new to this GitHub thing.

**Comment by acburst** [comment]
Yeh you can make a new pull request if you want

**Comment by haojia321** [comment]
https://github.com/Dogfalo/materialize/pull/4294 is the new one with right code format.

**Pull request closed without merging**
