### PR TITLE
Official Meteor integration

### PR DESCRIPTION
**Pull request by splendido**
Hello guys,

As you might know, the [Meteor](https://www.meteor.com/) community is loving Materialize. We have many different [wrapper packages](https://atmospherejs.com/?q=materialize) all doing the same thing but not all of them kept updated, so I'm submitting a PR that integrates Meteor packaging directly into your repository: at the end of this merge process, in case you'll find yourself comfortable with it, we'll get automated new Meteor package releases with every new release of Materialize.

I've made this PR as lean as possible so as not to take up too much space within your repository: basically it adds only a `package.js` file among the ones already present for other package managers.

All you have to do after accepting this PR would be:

1. Create an account at https://meteor.com/ (click SIGN IN, then Create account). After you've done that, please let me know the name of the account, and we'll add you as a maintainer of the *materialize* organization (which has been already reserved to make things simpler for you).

2. Head to [autopublish.meteor.com](http://autopublish.meteor.com/), sign in with your GitHub account, locate this repository and enable it for autopublish by toggling the checkbox you'll find on the right side of the repository item. You can get an idea about how Meteor Autopublish works by having a quick look at [this page](http://autopublish.meteor.com/howitworks), but basically it creates a [web hook](https://help.github.com/articles/about-webhooks/) to let us know when you push new tags. When you'll release new versions, autopublish.meteor.com will automatically package the the new version of the library also for Meteor!

3. In case you're not comfortable with autopublish.meteor.com maintaining access rights to your repos, please head to [GitHub Application Settings](https://github.com/settings/applications) and revoke permissions for *Meteor Autopublish*.

Please note that you will not be able to toggle your repository until you'll have the `package.js` file on your master branch.

Please also note that we've not yet published the current version of the package on [Atmosphere](https://atmospherejs.com) (Meteor's package directory) under the new name `materialize:materialize` to wait for your approval. If you think another name would be a better fit, just let us know!

Thanks in advance for your availability and collaboration and congratulation for the awesome project!
Luca & the [Meteor Packaging Team](https://github.com/orgs/MeteorPackaging/people)

### CODE REVIEW

**Comment by Dogfalo** [comment]
This sounds like something we definitely want to do. We will incorporate this in soon, thanks!

**Comment by splendido** [comment]
Great!
...we'll wait for progress news then :)

Tnx a lot,
Luca

**Comment by Dogfalo** [comment]
We have created an account. Username: materializecss

**Comment by splendido** [comment]
I've just added `materializecss` to the `materialize` organization, tnx!

is `materialize:materialize` fine as the package name? or would you prefer `materializecss:materializecss` or something else?

**Comment by Dogfalo** [comment]
`materialize:materialize` is good. Now ill take a look at intergrating the PR

**Comment by Dogfalo** [comment]
I think I have set everything up properly, but I did not see the packaged created on Atmosphere. Could you take a look and verify that everything was done correctly? Thanks!

**Comment by splendido** [comment]
Hei @Dogfalo,
you did it right, thank you very much!

You're not seing it on atmosphere because the first publish should be done by hands.
From now on next releases will be published automatically though :-)

**Comment by splendido** [comment]
Please see [materialize:materialize](https://atmospherejs.com/materialize/materialize)

**Comment by splendido** [comment]
Version 0.95.3 successfully autopublished! :-)
See it on [autopublish.meteor.com](http://autopublish.meteor.com/) and on [atmosphere](https://atmospherejs.com/materialize/materialize)

Thanks again!

**Pull request merged**
