### PR TITLE
autocomplete fixes and improvements

### PR DESCRIPTION
**Pull request by duszakpawel**
Hi,
there were a few problems with scalability of the autocomplete control and I have improved it on my own. Here is a list of new features that I have made:
- it is possible to populate the list multiple times; earlier it was bugged and the new list appeared on the first one
- when the list is expanded and the input loses focus the list is being collapsed like in normal drop-down list
- clicking in input results in expanding the list
- positioning of the expanded control has been fixed; when scrolling down the page it appears in the same place of the website, not window
- fixing some styles as well (width of list elements is equal to width of input)

I hope that my work will help to improve this library. I am looking forward for your response.

greetings from Poland,
Paweł Duszak

### CODE REVIEW

**Comment by kmmbvnr** [comment]
Looks like you replaced forms.js file with whole materialize.js content. That's definitely wrong.

**Comment by Koteczeg** [comment]
oh crap; edited

**Comment by acburst** [comment]
Why is the compiled CSS edited? You need to edit the sass and compile. It would be nice if you remade this pull request without the unnecessary commits.

**Comment by Koteczeg** [comment]
sorry, i couldn't find the place for css. I'll do it

**Comment by acburst** [comment]
I think you are looking for _input-fields.scss

**Comment by tomscholz** [comment]
@duszakpawel Are you still working on this? ^^

**Pull request closed without merging**
