### PR TITLE
non-breaking text

### PR DESCRIPTION
**Pull request by Rendemedum**
This way non-breaking text in the title, content, and comments has no adverse effects on layout or functionality

### CODE REVIEW

**Comment by DanielRuf** [comment]
Why should the default `word-wrap: normal;` be changed?

Your change has unexpected sie effects.

**Comment by Rendemedum** [comment]
non-breaking-text

Can you elucidate the unexpected side effects?
Would be nice to solve it within the Materialize Framework. Do you have another suggestion for it? 
I changed this in my stylesheet and it works.

**Comment by DanielRuf** [comment]
> I changed this in my stylesheet and it works.

This should be the only solution imho.

**Comment by Rendemedum** [comment]
That's a pity. I will dive into it. Keep up the good work.

**Pull request closed without merging**
