### PR TITLE
Color function optimization

### PR DESCRIPTION
**Pull request by TheGrimSilence**
## Changes
- Optimized color() in `_color.scss`
- Removed unneeded quotations across `$colors` map and all calls to `color()`
- Combined color and shade class functions

### CODE REVIEW

**Comment by developeranirudhprabhu** [comment]
@acburst and @Dogfalo can you please look into it?

**Comment by TheGrimSilence** [comment]
Consider it a small gift from Ebongarde Studios😉

**Comment by acburst** [comment]
You got rid of our warning for an incorrect color input. Have you tested input errors?

**Comment by TheGrimSilence** [comment]
Given that the colors are highly based on Google's color pallet the chance of 'new' and or 'changed' colors are low. But, if you feel cautious it can be added. Warnings are easy to avoid as long as you know what you're doing.

**Comment by Dogfalo** [comment]
It helps people debug if they have a typo in the color function

**Comment by TheGrimSilence** [comment]
Warning added back, code is safe.

**Comment by acburst** [comment]
That part of the code will never be executed? That was why we checked beforehand if the key existed so we could correctly return null with a warning. Right now it will only return null.

**Comment by TheGrimSilence** [comment]
If there's a typo, it'll give a warning. The error is as originally typed. Code runs fine. Same functionality.

**Comment by acburst** [comment]
I've just tested this with 3 cases:
 

```
color(xxx, base);
```
Which results in a compilation error.

```
color(xxx);
```
Which compiles, but does not raise the warning (which it should).
```
color(teal, xxx);
```
Which compiles, but does not raise the warning (which it should).

**Comment by TheGrimSilence** [comment]
Hm. I'll fix it
.

**Comment by TheGrimSilence** [comment]
Warning didn't work because I forgot to add the parent `@if map-has-key($colors, $color)`

**Comment by developeranirudhprabhu** [comment]
@acburst @Dogfalo Please look into it and do the needful

**Comment by tomscholz** [comment]
@DanielRuf Your thought on this, too?

**Pull request closed without merging**
