### PR TITLE
Fixing misleading details about tab selection api

### PR DESCRIPTION
**Pull request by lelandbatey**
Currently, [documentation on tabs](http://materializecss.com/tabs.html) says:

> You can programmatically trigger a tab change with our select_tab method. You have to input the ***id*** of the tab you want to switch to.   

Specifically:

> input the ***id*** of the tab

This is very false. [As you can see by the source here, selection of tabs has nothing to do with their id, and is instead entirely based on the contents of the `href` attribute of the element.](https://github.com/Dogfalo/materialize/blob/1f27f1162d0187c905bbb883bff15cf1e5e16a8f/js/tabs.js#L111)

I've updated the documentation here to be correct.

### CODE REVIEW

**Comment by Dogfalo** [comment]
See here

There are id's and they will also be the same as the href's, they are essentially the same thing

**Comment by lelandbatey** [comment]
@Dogfalo In the example code in the tutorials/in your screenshot, it is true that the `id`'s and the the `href`s are the same. Since they are the same, attempting to select based on the `id` will *appear* to work.

However, if the example html where changed so the `id`s are different from the `href`s and you attempt to select a tab now based on the `id`, the js will not work and the selection will not change.

So if the html where changed to the following:

```html
<div class="row">
	<div class="col s12">
		<ul class="tabs">
			<li class="tab col s3"><a href="#test1">Test 1</a></li>
			<li class="tab col s3"><a class="active" href="#test2">Test 2</a></li>
			<li class="tab col s3 disabled"><a href="#test3">Disabled Tab</a></li>
			<li class="tab col s3"><a href="#test4">Test 4</a></li>
		</ul>
	</div>
	<div id="testone" class="col s12">Test 1</div>
	<div id="testtwo" class="col s12">Test 2</div>
	<div id="testthree" class="col s12">Test 3</div>
	<div id="testfour" class="col s12">Test 4</div>
</div>
```

Given the above html, attempting to change the selected tab like so:

```javascript
$('ul.tabs').tabs('select_tab', 'testone');
````

This javascript will do nothing and no new tab will be selected.

**Comment by carlosperate** [comment]
I'm not quite sure your point is completely valid, as the example that you give breaks the tabs implementation altogether: http://codepen.io/anon/pen/pJxaKa
For it to work it needs to be the same code as the documentation: http://codepen.io/anon/pen/NqOyzg
In which case the id and href are essentially the same thing as indicated by @Dogfalo

**Comment by lelandbatey** [comment]
@carlosperate @Dogfalo  The context that I brought this issue up in was a project that made use of the tabs but without taking advantage of the built in ability to hide and show elements based on the currently selected tabs.

Revisiting this, I see that the way the mentioned project was using these tabs was not how they where intended to be used by the Materialize developers. I see now why the documentation for Materialize is the way it is. Thank you both for your comments!

**Pull request closed without merging**
