### PR TITLE
Modal top sheet style

### PR DESCRIPTION
**Pull request by inventti-leonardo**
You already have a modal bottom sheet style. Would be nice to have a modal top sheet style too :)

### CODE REVIEW

**Comment by tomscholz** [comment]
I don't get what you have done ;D

**Comment by inventti-leonardo** [comment]
@tomscholz like this:

https://s18.postimg.org/v8imy4quh/modal_top_sheet.png

**Comment by tomscholz** [comment]
Could you please add the changes that you did to the modals.html also to the modals_content file in `jade/page-contents/modals_content.html` ?

**Comment by inventti-leonardo** [comment]
@tomscholz done :)

**Comment by Dogfalo** [comment]
Ideally we don't add too many options and instead help people adhere to Material Design guidelines. Only bottom sheet is a standard android UI pattern. However if I see a few people request this, I'll be sure to direct them here to the work you've already done.

**Pull request closed without merging**
