### PR TITLE
Collapsible elements not in a list

### PR DESCRIPTION
**Pull request by johngeorgewright**
Any chance you'd consider changing the collapsible functionality so it doesn't require being in a list?

### CODE REVIEW

**Comment by PeggsDev** [comment]
:+1:

**Comment by tomscholz** [comment]
Make sure to check out the [CONTRIBUTING](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) document inside the root folder!

**Comment by jeroenqui** [comment]
Will this be accepted when implemented properly?

**Comment by tomscholz** [comment]
I see nothing that would speak against it

**Pull request closed without merging**
