### PR TITLE
Removed old Mixins section from the table of contents

### PR DESCRIPTION
**Pull request by tomscholz**
See https://github.com/Dogfalo/materialize/commit/72f2e944b9a600b8df49dcd0e2e404c48689aae8#commitcomment-23320603

### CODE REVIEW

**Comment by DanielRuf** [comment]
Should we still keep the unused / empty mixins file? For me it makes no sense to keep it.

**Comment by DanielRuf** [comment]
https://github.com/Dogfalo/materialize/blob/master/sass/components/_mixins.scss

**Comment by Dogfalo** [comment]
We don't need it anymore,

**Comment by Dogfalo** [comment]
Also remove mixins from being imported in `materialize.scss`

**Pull request merged**
