### PR TITLE
Lets update the documentation for navbar search.

### PR DESCRIPTION
**Pull request by drainx**
How about a fix for #1669 . Just because it works in master doesn't mean the docs shouldn't be updated. It in fact does not work as intended in master, which was the whole point of that issue in the first place.

Signed-off-by: Daniel Rix <Drainx1@live.com>

### CODE REVIEW

**Comment by Dogfalo** [comment]
You are using the wrong icon files

**Comment by drainx** [comment]
Please elaborate.
It is clearly broken as pointed out in #1669, and this is the appropriate fix for it, again as stated in #1669

**Comment by carlosperate** [comment]
You are pulling in the use of the old icons. The google material icons should be used instead: http://materializecss.com/icons.html

**Comment by drainx** [comment]
So then why is it broken on the main site, which is using that icon family?

**Pull request closed without merging**
