### PR TITLE
Integrate BrowserSync

### PR DESCRIPTION
**Pull request by drKraken**
Suggest using a browserSync instead of connect. Its more flexible, faster and reusable.
https://github.com/shakyShane/browser-sync

### CODE REVIEW

**Comment by Dogfalo** [comment]
Tried it out, seemed much slower than connect. I may have set it up wrong but it took around 6 seconds for the server to start

**Comment by drKraken** [comment]
It starts a little bit slower but it contain live reloading that work much faster for me than other one and allow to test page in different browsers easily. See it in action https://www.youtube.com/watch?v=Rv5f_v5gqw4

**Comment by TimonVS** [comment]
I agree with @drKraken. Live reloading (CSS injection instead of reloading the whole page) across browsers is a huge plus.

**Comment by Dogfalo** [comment]
Updated to browser sync 2.5. Seems faster now and the UI is nice! Made a few changes, but thanks for the PR!

**Pull request merged**
