### PR TITLE
Added text-align justify property and removed the error of disabled links can be clicked. #3835

### PR DESCRIPTION
**Pull request by TheAvinashSingh**
There is no option to justify align text.
There is kinda class named "toast" which justifies text but gives a black background.
So I added a simple class named "text-justify" to align text to justify.

### CODE REVIEW

**Comment by avinash97** [comment]
Will you take a look here @Dogfalo and @acburst .

**Comment by tomscholz** [comment]
Have a look at our [CONTRIBUTING guide here](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) Never commit compiled files. We compile them with every version bump.

**Comment by TheAvinashSingh** [comment]
Okay. I will take care of this.

**Comment by tuxredux** [comment]
Definitely think this is needed... Perhaps change the class name to `justify-align` to go along with the [Text Align Helpers](http://materializecss.com/helpers.html) convention?

**Comment by TheAvinashSingh** [comment]
Ya, there isn't any pre defined class available for CSS = text-align:justify;
They should add it with justify-align as you should.
@acburst Could you please check this out.

**Pull request closed without merging**
