### PR TITLE
Fix Dependency 'jquery' exists in both dependencies

### PR DESCRIPTION
**Pull request by listepo**

### CODE REVIEW

**Comment by tomscholz** [comment]
Your pull request body is empty. 
Please add more information in order to allow us to undestand why you did the changes.

**Comment by DanielRuf** [comment]
@tomscholz it is about one of the warnings of npm. jQuery is in the dev and normal dependencies, but should be not in the dev dependencies.

**Comment by tomscholz** [comment]
^^

**Comment by DanielRuf** [comment]
For example https://travis-ci.org/Dogfalo/materialize/builds/224550673#L153 ;-)

We should cleanup and update the dependencies in the near future and move to node.js 6.x LTS =)

**Comment by tomscholz** [comment]
See https://github.com/Dogfalo/materialize/pull/4587

**Pull request closed without merging**
