### PR TITLE
Corrected a typo in typography.html

### PR DESCRIPTION
**Pull request by sahildua2305**

### CODE REVIEW

**Comment by Dogfalo** [comment]
Fixed in 56e1c78b955d1372b7abf1b5cbe1ec67621579c0

**Comment by sahildua2305** [comment]
@Dogfalo any reason for not merging and making the same change otherwise?

**Comment by Dogfalo** [comment]
https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md

**Comment by sahildua2305** [comment]
Ah! My bad. Sorry!

**Pull request closed without merging**
