### PR TITLE
Focused active preloader sass to direct child

### PR DESCRIPTION
**Pull request by nmggithub**
## Proposed changes

This fixes a bug where spinners inside a collapsible will always stay on, because the parent list item will have the class "active".

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by nmggithub** [comment]
This has been sitting here for several months. This is a very minor change. Can someone please look at it?

**Comment by Smankusors** [comment]
> This has been sitting here for several months. This is a very minor change. Can someone please look at it?

this repo... idk...

but if you want, you can contribute to the forked one instead https://github.com/materializecss/materialize 😉

also, consider adding an example/a codepen/the screenshots, it will help maintainers see what's the problem are.

**Comment by nmggithub** [comment]
> > This has been sitting here for several months. This is a very minor change. Can someone please look at it?
> 
> this repo... idk...
> 
> but if you want, you can contribute to the forked one instead https://github.com/materializecss/materialize 
> 
> also, consider adding an example/a codepen/the screenshots, it will help maintainers see what's the problem are.

I'll take a look. Thanks for turning me onto it.

**Comment by nmggithub** [comment]
Finally closing this. Nothing was ever done with it.

**Pull request closed without merging**
