### PR TITLE
copy tasks to put picker where its required

### PR DESCRIPTION
**Pull request by nicosommi**
A temporal fix for
https://github.com/Dogfalo/materialize/issues/3139
and
https://github.com/Dogfalo/materialize/issues/1422

The thing is that when you run for example your tests you get 'Cannot find the module ./picker.js'. That's because the concat task on the Gruntfile does not do anything with the paths within require calls.
It is just two lines to copy the two extra files on those paths so the require works on node.js, the other differences are just because consequence of running the release tasks.

This is a temporal fix because it may be better to remove or take a different solution for this problem and I don't have the proper context to clearly see that. But this is literally making users choose a different tool.

### CODE REVIEW

**Comment by nicosommi** [comment]
Recents pull requests are failing all because of the same thing: a failing test regarding to a tooltip test

**Comment by acburst** [comment]
Yep, that is my bad. I just fixed this, you can sync and try again

**Comment by nicosommi** [comment]
all right now it's in sync thanks @acburst

**Comment by june07** [comment]
When is this going to be merged?  It seems the issue remains.

**Comment by june07** [comment]
Actually, not sure why all those other files were changed?!  Please see the PR I just submitted: https://github.com/Dogfalo/materialize/pull/4158.  Thanks.

**Comment by nicosommi** [comment]
@june07 all right then I will close this one. Yes I forgot to stash some things I've done test the buils and the changes.

**Pull request closed without merging**
