### PR TITLE
Update sidenav_content.html

### PR DESCRIPTION
**Pull request by dev10110**
It took me a while to realise this one line (missing default options argument) was the reason the default code wasn't working. Hopefully, this helps the next dodo like me :)

## Proposed changes
Modified example to make it runnable by copy-paste

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

Documentation update

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

There should be no changes to the main codebase. 
Im not sure why Github is saying im changing line 394, I don't think I am.

### CODE REVIEW

**Comment by roiLeo** [comment]
You are missing a new line at end of file.

**Comment by dev10110** [comment]
@roiLeo Right of course! I've fixed it now, so the PR is just a single additional line in the documentation. Does someone need to review it before merging it into the main documentation?

**Comment by Smankusors** [comment]
welp there's a problem on this repo.... hmm look at #6438

feel free to create new PR at https://github.com/materializecss/materialize 😉

**Comment by dev10110** [comment]
haha cool, it's here https://github.com/materializecss/materialize/pull/19 (linked for future reference)

**Pull request closed without merging**
