### PR TITLE
Feature request: Autocomplete Update

### PR DESCRIPTION
**Pull request by SuperDJ**
As seen here: [https://www.google.com/design/spec/components/text-fields.html#text-fields-auto-complete-text-field](https://www.google.com/design/spec/components/text-fields.html#text-fields-auto-complete-text-field) a autocomplete could have icons.

I came up with the following:

Still todo:
- fix bugs in highlighting (
image

)
- add support for images with highlighted text

**Autocomplete is working fine. Highlighted text option could be removed**

### CODE REVIEW

**Comment by lastnoob** [comment]
How can I use this with the CDN? what should I add to the css and js?

**Comment by SuperDJ** [comment]
@lastnoob this hasn't been merged (yet) so you can't use it (yet)

**Comment by kristoftorfs** [comment]
Any ETA on merging?

**Comment by SuperDJ** [comment]
@kristoftorfs at least I don't know anything about an ETA and because of the lack of merges and bug fixes lately I started my own

**Comment by SuperDJ** [comment]
@Dogfalo @acburst Could this please be merged because people start forking it from me which could ultimately result in people not getting other updates of materialize

**Comment by SiliticX** [comment]
@SuperDJ ETA on the fixes? I really really hope this is going to be merged soon. We have a project that actually needs autocomplete and we just realised, 5 days before beta, that this is not in yet. I will be tagging myself to know the progress on this... we will have to use select2 meanwhile :(

**Comment by SuperDJ** [comment]
@SiliticX I can tell you that I'm not going to create a PR again for this any time soon. I also wished they had merged this already but sadly they haven't. In the mean time you can add the following code.

In forms.js. Note that I deleted the functions for highlighting text because it didn't work 

               /**************************
		 * Auto complete plugin  *
		 *************************/
		$(input_selector).each(function() {
			var $input = $(this);

				if( $input.hasClass('autocomplete') ) {
					var $array = $input.data('array'),
							$inputDiv = $input.closest('.input-field'); // Div to append on

					// Check if "data-array" isn't empty
					if( $array !== '' ) {
						// Create html element
						var $html = '<ul class="autocomplete-content hide">';

						for( var i = 0; i < $array.length; i++ ) {
							// If path and class aren't empty add image to auto complete else create normal element
							if( $array[i]['path'] !== '' && $array[i]['class'] !== '' ) {
								$html += '<li class="autocomplete-option"><span>'+$array[i]['value']+'</span></li>';
							} else {
								$html += '<li class="autocomplete-option"><span>'+$array[i]['value']+'</span></li>';
							}
						}

						$html += '</ul>';
						$inputDiv.append($html); // Set ul in body
						// End create html element

						// Perform search
						$(document).on('keyup', $input, function () {
							var $val = $input.val().trim(),
									$select = $('.autocomplete-content');
							// Check if the input isn't empty
							if ($val != '') {
								$select.children('li').addClass('hide');
								$select.children('li').filter(function() {
									$select.removeClass('hide'); // Show results

									return $(this).text().indexOf($val) !== -1;
								}).removeClass('hide');
							} else {
								$select.children().addClass('hide');
							}
						});

						// Set input value
						$('.autocomplete-option').click(function() {
							$input.val($(this).text().trim());
						});
					} else {
						return false;
					}
				}
			});

For styling you can simply add the scss below in your own stylesheet:

    // Auto complete
    .autocomplete-content {
	margin-top: -1rem;
	@extend .z-depth-1;

		li {
			clear: both;
			color: rgba(0, 0, 0, 0.87);
			cursor: pointer;
			line-height: 1.5rem;
			width: 100%;
			text-align: left;
			text-transform: none;

			> span {
				color: $input-focus-color;
				font-size: 1.2rem;
				padding: 1rem;
				display: block;

				.highlight {
					color: #000000;
				}
			}

			img {
				height: 52px;
				width: 52px;
				padding: 5px;
				margin: 0 15px;
			}



			&:hover {
				background: #eee;
				cursor: pointer;
			}
		}
     }

**Comment by SuperDJ** [comment]
@lastnoob @kristoftorfs @SiliticX Maybe you can make an issue of this if you need it

**Comment by SiliticX** [comment]
@SuperDJ Thanks!

**Comment by denisdenes** [comment]
Hi, any update on this?

**Comment by dgonzalezr** [comment]
Hey guys, this is a good feature, and now days very useless, any updates when it can be available??

**Comment by acburst** [comment]
Thanks again for this work SuperDJ. I simplified and cleaned up the code a bit

**Comment by akosbordas** [comment]
when will it be released?

**Comment by nitoloz** [comment]
+1

**Comment by quentinHydrobat** [comment]
+1
Anyone can update documentation ? A little *How-to* in form would be great

**Pull request merged**
