### PR TITLE
Added option to dropdown, to allow the menu to expand upwards instead.

### LINKED ISSUE #960: long dropdown trimmed by viewport bottom edge
I figured out how to avoid this problem with right and left edges. But with a long dropdown list, for example 24 hours, the bottom part of the list is trimmed and not accessible. See attached.
dropdown

### PR DESCRIPTION
**Pull request by madsnedergaard**
This pull-request fixes #960 and possibly the duplicates #780 and #903.
It adds an option to make the menu appear above the activator. It might need more testing and I haven't changed the animation to slide upwards instead of down, but I hope it might be useful anyway.

### CODE REVIEW

**Comment by donwojtallo** [comment]
+1
I found this very useful.

**Comment by donwojtallo** [comment]
I made version with dropup with position relative to bottom to improve animation. Maybe it's not Material style, but now it animates way better.
See my changes:
https://github.com/donwojtallo/materialize/commit/12c1d940587a935bfc25f88f4f211951b028d366
P.S. sorry for tabs. Stupid editor.

**Comment by jhillhouse92** [comment]
What's the status of this pull request? Will it be merged?

**Comment by Dogfalo** [comment]
Dropdowns should go upwards is when there is no room on the screen left

**Pull request closed without merging**
