### PR TITLE
Bug select unselecting option

### PR DESCRIPTION
**Pull request by alejandrovasta**
Fixing unselecting options in the material select. When a user unselect an option, the selected option attribute is not updating its selected property as false.

### CODE REVIEW

**Comment by acburst** [comment]
Not sure what issue you are fixing here. Do you have a code example of your issue? I don't really know what unselecting an option is supposed to be doing.

**Comment by alejandrovasta** [comment]
Hi Alan!, I detected when you unselect a option in a multiple select, the selected attribute doesn't change.  It is always true. If you print the $('your-select').val() you can see that its value is even the same.

**Comment by acburst** [comment]
Have you tried reproducing this bug on the latest version of master? We've merged in a couple of PRs and I think this issue is fixed, but let me know if youre still having problems on current master.

**Comment by TyrionGraphiste** [comment]
Hi @acburst , this PR fix these issues :

https://github.com/Dogfalo/materialize/issues/2458
https://github.com/Dogfalo/materialize/issues/2274

Some opened issues are fixed yet :

https://github.com/Dogfalo/materialize/issues/2265

However, this https://github.com/Dogfalo/materialize/issues/1707 issue isn't yet solved.
Hope this message could help you.

**Comment by acburst** [comment]
Thanks for this @alejandrovasta. And thanks for organizing issues @TyrionGraphiste

**Comment by alejandrovasta** [comment]
Thanks to you @acburst for your awesome work ;-)

**Pull request merged**
