### PR TITLE
Fix custom error/success messages

### LINKED ISSUE #2525: [Bug] Form custom error/success messages
Hi,

Custom error or success messages replace spaces in string with line return ! Is it a correct behavior ?

screen shot 2015-12-22 at 12 24 30

Thanks

### PR DESCRIPTION
**Pull request by Zevran**
Wrong behavior with messages containing spaces
Resolve #2525

### CODE REVIEW

**Comment by remzr7** [comment]
+1

**Comment by Dogfalo** [comment]
Hmm `nowrap` may not be the best solution. If you had a long error message, it would not line wrap properly. I think the better change is to set the label width to 100%

**Comment by Gskartwii** [comment]
+1

**Comment by Dogfalo** [comment]
This has been fixed

**Pull request closed without merging**
