### PR TITLE
Added container option to timepicker, issue #4900

### LINKED ISSUE #4900: Timepicker container option
### Description
Materialize timepicker option container now working.

### Example
```
$('.timepicker').pickatime({
 container: '#div'
  });
```
### Solution
Is there any solution e.g. .appedTo('body') ?

### PR DESCRIPTION
**Pull request by Y0lk**
Makes sense to have the container option, fixes #4900

### CODE REVIEW

**Comment by Dogfalo** [comment]
appending after the input needs to be the default

**Comment by Y0lk** [comment]
Wouldn't it make sense for it to have the same behavior as the datepicker by default though? The datepicker gets added to the body

**Comment by Y0lk** [comment]
Nevermind, I'm wrong. Will update the pull request right away

**Comment by Y0lk** [comment]
done

**Comment by Dogfalo** [comment]
Won't  `if(this.options.hasOwnProperty('container'))` always return true here?

**Comment by Y0lk** [comment]
It won't because the option isn't defined in the defaults, so if you don't specify the container, the property doesn't exist and it'll default to adding it after input. I did it this way simply because that's exactly the way it's implemented in materialize clockpicker.

We could change this to check for an empty string if you prefer (and have the default container option as empty string)

**Pull request merged**
