### PR TITLE
Added Grunt tasks to put picker in dist/ and bin/

### PR DESCRIPTION
**Pull request by june07**
Duplicate of:
https://github.com/Dogfalo/materialize/pull/3355/commits/020046cc5cd777fe435091082bf0ce8867667c5e

### CODE REVIEW

**Comment by june07** [comment]
Is this going to be merged?  Or has it otherwise been resolved?

**Comment by tomscholz** [comment]
Why does the needs to be merged? What is the benefit?

**Comment by DanielRuf** [comment]
Can we test the branch and merge this?

**Comment by june07** [comment]
Anyone?

**Comment by Dogfalo** [comment]
Why do we need this?

**Comment by june07** [comment]
Please read the thread.  It is causing problems for multiple users of the
library.

**Comment by DanielRuf** [comment]
It is for the loader scripts, especially the npm module which looks for these files locally.

@tomscholz can you or someone else make a failing test which is fixed by this PR?

**Comment by DanielRuf** [comment]
Was the PR obsolete @tomscholz? Did not see why it was reverted. If there is an issue I can take a look at it.

**Pull request merged**
