### PR TITLE
Character count and Sidenav issues fixed

### LINKED ISSUE #1612: Character Count works with invalid html attribute
The character counter works with an invalid html attribute (length) instead of using maxlength or a data-attribute.

I couldn't find the length anywhere in the specs (http://www.w3.org/TR/html5/forms.html#the-input-element). I'm using React which eliminates all attributes that are not in the specs.

In case you guys would like to get this solved, I'm more than willing to transform it towards whichever option (maxlength or data-) has your preference.

### PR DESCRIPTION
**Pull request by janpieterz**
Fixed #1612 and #1426.

With #1612 I chose for using a data attribute, since the maxlength attribute would prohibit the user from getting the validation errors and feels a bit too restrictive (it would never show the red invalid line). 

In case you want me to make any other changes to this just let me know!

### CODE REVIEW

**Comment by mondaychen** [comment]
+1 for this. I hate the fact that a fixed SideNav for desktop will also be closed when `closeOnClick` enabled.
But probably a separate option is better? Some people may still need it on desktop version

**Comment by janpieterz** [comment]
@mondaychen ideas for naming? preventCloseOnClickOnDesktop: true ?
Seems a little bit too extensive, though it describes exactly what happens ;)

**Comment by janpieterz** [comment]
I've also added a small css fix. A pagination element was only clickable on it's link element, while the whole li had a pointer.

**Comment by mondaychen** [comment]
How about turn the option `closeOnClick` into [Boolean or Function], instead of just Boolean?
Like this:
````
options.closeOnClick = $.isFunction(options.closeOnClick) ?  options.closeOnClick() : options.closeOnClick
````
In this way it keeps the current behavior as it is. And when you need to prevent it on desktop version, you can use
````
$('.button-collapse').sideNav({
    closeOnClick: function() { return window.innerWidth <= 992; }
});
````

**Comment by janpieterz** [comment]
@mondaychen I'll wait for the official dev's to pitch in so I'm not working on it too much without any guidance on how they'd like it. Thanks for the idea, would never have thought of doing it that way myself, neat way!

The other commit just added ensures the ability to call .characterCounter() multiple times over the same form without creating two elements. I came onto this in my react app which updated the view dynamically, calling the method then would result in a double element being created since the plugin already initializes itself.

Other solutions I currently see are:
Doing it at the top of the .each function, making sure we don't double-monitor and execute the character counting (cleaner but wasn't sure if this was wanted)
Removing the initial call from the library which then forces every single user to call it manually.

**Comment by tomscholz** [comment]
#1426 fixed in https://github.com/Dogfalo/materialize/commit/f97bf0b5e4061b10c5e6a9624de97f138583c003

**Comment by tomscholz** [comment]
I'm going to close this pull request now because it's very old and some things are already fixed in the master branch. Any new discussion should probably happen on a new issue with a more specific title!

**Pull request closed without merging**
