### PR TITLE
Make Entire Framework RTL

### PR DESCRIPTION
**Pull request by hadjloo**
Using RTLit library, all scsses became RTL

No calue or code changed, only css commands replaced by RTLit mixins

I also added A new Materialze-RTL.scss which let you use RTL library

to use RTL version, you need to use RTL version

To use in RTL mode, only and Only the front-end designer should use default LTR mode, in RTL, everything would become vice versa

### CODE REVIEW

**Comment by hadjloo** [comment]
Please review and close this pull request as soon as possible, so that new code, uses new approach.

You can test it via your online demo, simply replace materialize-rtl.css, with the default materialize.css

for datepicker, I wanted to add other localizations, but I couldn't find out how to add new logic to it, please let me know how can I add new Calendar mode (Hebrew or Arabic), I will do the rest

let me know if there is any question

Regards

**Comment by hadjloo** [comment]
This Pull request will should answer following problem

1.  https://github.com/Dogfalo/materialize/issues/3002
2.  https://github.com/Dogfalo/materialize/pull/3187
3.  https://github.com/Dogfalo/materialize/issues/2824
4.  https://github.com/Dogfalo/materialize/pull/2494
5.  https://github.com/Dogfalo/materialize/issues/2175
6.  https://github.com/Dogfalo/materialize/issues/1892
7.  https://github.com/Dogfalo/materialize/issues/1743

I'm not sure if this can help fix following issues to

1. https://github.com/Dogfalo/materialize/issues/3414
2. https://github.com/Dogfalo/materialize/issues/3037
3. https://github.com/Dogfalo/materialize/pull/1795

If I could add a new culture for datepicker then I can fix follwing issues\

1. https://github.com/Dogfalo/materialize/issues/2639

**Comment by mortadda** [comment]
you can change tab direction to rtl by change flowing code in  materialize.js  Line:3051:
` // Update indicator
                    if (($index - $prev_index) >= 0) {
                        $indicator.velocity({"left": $tabs_width - (($index + 1) * $tab_width)}, {
                            duration: 300,
                            queue: false,
                            easing: 'easeOutQuad'
                        });
                        $indicator.velocity({"right": $index * $tab_width}, {
                            duration: 300,
                            queue: false,
                            easing: 'easeOutQuad',
                            delay: 90
                        });

                    }`

**Comment by sepehr1014** [comment]
@hadjloo Thank your for your awesome work. Is this production ready or are there major bugs I should be aware of?

**Comment by Dogfalo** [comment]
I think this is best left as 3rd party work because this adds on a lot of complexity and maintenance work. I can tell this has a lot of good work so I will try to redirect people here when they inquire about an RTL version.

**Comment by sepehr1014** [comment]
@Dogfalo It's sad to hear it's not going to be integrated into the library though I understand the reason.
@hadjloo It'd be great if you could create a separate repository and maintain the RTL version of Materialize ...

**Comment by gdoron** [comment]
@Dogfalo @hadjloo @sepehr1014  I think it would be better if it wouldn't be in a different repository, but additional SCSS file that would be added as part of the build.

If it will be in a fork, the repo will go out of sync very fast...

**Comment by sepehr1014** [comment]
@gdoron Actually I couldn't agree more. It would be awesome to have it as part of the library. But if it's not going to happen, then a fork is better than nothing at all.

**Comment by gdoron** [comment]
@sepehr1014  @hadjloo The point I'm trying to make here is, the changes shouldn't be inside the framework files at all.

For example, there shouldn't be changes in `_buttons.scss` but add `_rtlButtons.scss` with overrides.
It doesn't matter a whole lot if it will be maintained in the same repository or not.

The `_rtl*.scss` files should override\add rules only if the body has a class of "rtl".

This is how I would have done it, it's easy to maintain and easy to dynamically make changes on live within the app.

**Comment by arminmon** [comment]
I've been working on a _rtl_support.scss component (only needs to be imported inside materialize.scss) that will make elements RTL by just adding the .rtl class to their parents. It's a work in progress because I'm developing it on demand for a RTL web design.
It's available in one of my repositories. If anyone's interested, we can start developing it as a component for Materialize.

**Comment by gdoron** [comment]
@arminmon you should talk with @Dogfalo maybe you can find a way to add it to the framework repository.
That's really the best option here.

**Comment by arminmon** [comment]
@gdoron I just forked a new branch. I'll be requesting it as a pull soon.

**Pull request closed without merging**
