### PR TITLE
Make page-footer use $primary-color

### PR DESCRIPTION
**Pull request by tscolari**
It's currently hard-coded to color("materialize-red", "lighten-2")

### CODE REVIEW

**Comment by snow01** [comment]
I would say rather than again hard-coding it to use $primary-color - it's better to define another variable for footer color, with a fallback to $primary-color

**Comment by tscolari** [comment]
@snow01 I agree.
I believe the best would probably do like twt-bootstrap does, have variables for all the customizable aspects, not only for colors.

**Comment by snow01** [comment]
True. I suggest if you can re-submit your pull request after changing footer color as I suggested above. I will also submit pull request for a few customization I did. I think slowly and steadily we can achieve a higher customization.

**Comment by acburst** [comment]
Added in 45c7118a25a3cd43a59df88b714154e9fd534284

**Comment by acburst** [comment]
Thanks!

**Pull request closed without merging**
