### PR TITLE
SideNav menu was moving on X-axis

### PR DESCRIPTION
**Pull request by alexisdiel**
when menu contents overrides the height

### CODE REVIEW

**Comment by DanielRuf** [comment]
Fixes https://github.com/Dogfalo/materialize/issues/4814

PS: overflowY without quotes should also work.

**Comment by DanielRuf** [comment]
This is the wrong file, please change the right lines in the sidenav.js file.

**Comment by acburst** [comment]
I agree with @DanielRuf. I believe there is something wrong with the css that is causing this error and changing the overflow is not the way to go fixing this.

**Comment by tomscholz** [comment]
https://github.com/Dogfalo/materialize/commit/a8d472fca1abf72afa638aa5e7e9bf1882d9cd15

**Pull request closed without merging**
