### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by tomscholz**
* Removed the _SpecRunner.html file since it’s automatically generated when running the jasmine tests.
* I also talked to Jason, who owns the grunt-rename-util(prev. grunt-contrib-rename), to update the package to be compatible with grunt 1.0.0
* Updated the node engine, because since 2016-12-31
 the support has ended

### CODE REVIEW

**Comment by DanielRuf** [comment]
I guess we need another setTimeout + done() callback there? https://github.com/Dogfalo/materialize/blob/master/tests/spec/tabs/tabsSpec.js#L76

**Comment by tomscholz** [comment]
@DanielRuf Oh man. I just saw this now. 

Like this?
```
    it("should horizontally scroll when too many tabs", function () {
      var tabsScrollWidth = 0;
      normalTabs.parent().css('width', '400px');
      normalTabs.find('.tab').each(function() {
        tabsScrollWidth += $(this).width();
      });

      setTimeout(function() {
        expect(tabsScrollWidth).toBeGreaterThan(normalTabs.width(), 'Scroll width should exceed tabs width');
        done();
      }, 400);
    });

  });
});
```

**Comment by DanielRuf** [comment]
Try this

```
it("should horizontally scroll when too many tabs", function (done) {
      var tabsScrollWidth = 0;
      normalTabs.parent().css('width', '400px');
      normalTabs.find('.tab').each(function() {
        tabsScrollWidth += $(this).width();
      });

      setTimeout(function() {
        expect(tabsScrollWidth).toBeGreaterThan(normalTabs.width(), 'Scroll width should exceed tabs width');
        done();
      }, 400);
    });

  });
});
```

**Comment by tomscholz** [comment]
🤔 Well... that doesn't work. @acburst you wrote that test. I don't get why "Scroll width should exceed tabs width" is a thing. Tabs have the same width when they are scrollable or not.

**Comment by DanielRuf** [comment]
There beeds to be a timeout until the styles are applied. Did you test locally using Grunt? The test should not fail with the aforementioned fix. At least this workaround helped to fix other tests.

**Comment by DanielRuf** [comment]
`grunt travis --filter=tabs` should help with local tests. It might be that another timeout is needed around the

```
normalTabs.find('.tab').each(function() {
        tabsScrollWidth += $(this).width();
      });
```

after the `.css()` code. I will test this here with your branch in about an hour.

**Comment by tomscholz** [comment]
@DanielRuf I know. I was running the test locally, before I pushed them!

**Comment by DanielRuf** [comment]
Ok. So on your system the test in the branch did not fail? Will test it here on Windows. Might be that the PhantomJS driver and the headless webkit on Travis under Linux is a bit slower (at least the free plan has less power than the paid ones)?

**Comment by tomscholz** [comment]
@DanielRuf Well, I may sound like an idiot now, but no, the test did fail on my local machine.

**Comment by DanielRuf** [comment]
Then the change did nothing as it should havr fixed the failing test ;-) I will check this for you.

**Comment by tomscholz** [comment]
@DanielRuf Looks good to me. What do you think?

**Comment by DanielRuf** [comment]
Not sure why we need the changes in the package file as some tools still use them.
So far the other things look good to me.

http://stackoverflow.com/questions/32037150/style-field-in-package-json
https://www.npmjs.com/package/npm-sass

**Comment by DanielRuf** [comment]
It should be easy to revert the last commit as this one would break many implementations / projects ;-)

**Comment by DanielRuf** [comment]
Looks good =)

**Pull request merged**
