### PR TITLE
Added flat navigation bar option

### PR DESCRIPTION
**Pull request by penguoir**
By adding the class `.flat` to a navigation bar, the navigation bar looses its box shadow and becomes "flat".

### CODE REVIEW

**Comment by DanielRuf** [comment]
What are good reasons for this? Normally a navbar is elevated and not on the same level as the content.

I will check the material design specs if this makes sense and check the other components.

Also please add this change to the docs in the jade directory so this would be mentioned in the docs if it would be merged.

**Comment by tomscholz** [comment]
Spec: https://material.io/guidelines/layout/structure.html#structure-app-bar

**Comment by penguoir** [comment]
This feature can be used when using a transparent navigation bar. Nobody wants a shadow from a transparent element.

**Comment by tomscholz** [comment]
I would change it to transparent. Flat is misleading since there is no official spec for flat.

**Comment by penguoir** [comment]
Sorry, I don't understand. Change the name to "transparent", remove shadow from the transparent navigation bar or something else?

**Comment by DanielRuf** [comment]
So soecifically it is not flat but transparent according to the specs?

Should we use another class for this or `.flat` to be more precise?

**Comment by penguoir** [comment]
Perhaps a `.flat` class which just removes shadow and a `.transparent` class which turns the navigation transparent as well as removing shadow?

**Comment by fega** [comment]
What about z-depth-0?

**Comment by tomscholz** [comment]
@fega Well, you are a genius

**Comment by DanielRuf** [comment]
The current change is just the z depth class http://materializecss.com/shadow.html
https://github.com/Dogfalo/materialize/pull/4683/files

We should use transparent and set the background color to transparent (maybe).

**Comment by DanielRuf** [comment]
And the background?

**Comment by penguoir** [comment]
`.transparent` already has a selector in colours.scss, no need to repeat the same selector.

**Comment by DanielRuf** [comment]
> .transparent already has a selector in colours.scss, no need to repeat the same selector.

Ah, right. Forgot to check that there :D

**Comment by acburst** [comment]
I don't see the point of a flat class if you can add a z-depth-0 class?

**Comment by DanielRuf** [comment]
> I don't see the point of a flat class if you can add a z-depth-0 class?

Right. And combine this with the transparent class.

I guess it is better to just add an example with these classes to the docs.

**Comment by tomscholz** [comment]
We are currently not adding this into our core framework. It is easy enough to customize yourself.

**Pull request closed without merging**
