### PR TITLE
hotfix/code-improvements-on-parsing

### PR DESCRIPTION
**Pull request by chukitow**
Parsing integers in this way is faster. Take a look at this.

``` javascript
console.time("parseInt1");
for(var i=0; i<=10000;i++){
  var length = parseInt("100");
}
console.timeEnd("parseInt1");

console.time("parseInt2");
for(var i=0; i<=1000;i++){
  var length = +"100";
}
console.timeEnd("parseInt2");
```

### CODE REVIEW

**Comment by tiekuhn** [comment]
proven by jspertest. Please see
http://jsperf.com/parsing-integers-test

**Comment by tomscholz** [comment]
@DanielRuf

**Comment by DanielRuf** [comment]
Direct type casting (using unary plus, double NOT bitwise, right shift unsigned and other bitwise operators) is generally faster than parseInt and other high level abstractions in programming languages.

The PR looks good.

**Comment by acburst** [comment]
First off, your console test don't use the same amount of iterations. And second, the time saved is definitely negligible given the amount of times these parseInts are going to be called. I think its fine to stay with parseInts because they are definitely more legible and make the code more readable.

**Pull request closed without merging**
