### PR TITLE
Fix typo in forms.html

### PR DESCRIPTION
**Pull request by kevgathuku**

### CODE REVIEW

**Comment by Dogfalo** [comment]
Please edit the file in jade/page-contents instead

On Wed, Feb 18, 2015 at 4:30 PM, kevgathuku <notifications@github.com>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Dogfalo/materialize/pull/714
> Commit Summary
>
>    - Fix typo in forms.html
>
> File Changes
>
>    - *M* forms.html
>    <https://github.com/Dogfalo/materialize/pull/714/files#diff-0> (4)
>
> Patch Links:
>
>    - https://github.com/Dogfalo/materialize/pull/714.patch
>    - https://github.com/Dogfalo/materialize/pull/714.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/pull/714>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by kevgathuku** [comment]
Okay. Let me do that.

**Comment by kevgathuku** [comment]
@Dogfalo I've edited the correct file.

**Comment by Dogfalo** [comment]
Thanks!

**Comment by kevgathuku** [comment]
You're welcome :+1:

**Pull request merged**
