### PR TITLE
Reimplement closeOnSelect functionality and set default to false

### PR DESCRIPTION
**Pull request by jacobau**
This has been an issue that has been hanging around for a while and the fix is super easy.

To align with material design principles, default has been set to false but allows people to enable it without the `for ('select' in args)` hacky workaround that exists.

#870

### CODE REVIEW

**Comment by wackychocolatefactory** [comment]
Thoughts?

**Comment by developeranirudhprabhu** [comment]
@acburst @Dogfalo Please look into it and do the needful

**Comment by jacobau** [comment]
Anyone?

**Comment by tomscholz** [comment]
Hey there 👋 
We are happy to see, that you have created a pull request to fix a problem or add a feature or did something else.
Unfortunately does your PR include compiled files. Please do not edit materialize.css, materialize.js or any .html file directly! Those files are automatically generated. You should edit the source files in the locations below instead. Also make sure to check out our [CONTRIBUTING GUIDE](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)!
```
/materialize/sass/
/materialize/js/ 
/materialize/jade/page-contents/ 
```
We won't look into this, unless you modify your PR, so that it matches with our CONTRIBUTING guidelines.

**Comment by pain0486** [comment]
So if he removes the alterations to forms.html can this solution be merged?

**Comment by tomscholz** [comment]
Added in https://github.com/Dogfalo/materialize/commit/b17ad0b2876739d4c18f38ba3051e8cc6cb89e8f

**Pull request closed without merging**
