### PR TITLE
Added missing fixed navbar documentation

### LINKED ISSUE #1664: navbar-fixed AND mobile collapsable menue.
Hi!
This is a promising framework, I like it!
I wonder though, it seems like there is no solution for having both the `navbar-fixed` and also use the `nav-mobile` `button-collapse`. As of now, the z-indexes is disturbing each other. 
##### The error:

When the collapse mobile nav is pulled out, the fixed-navbar (at the top) is "above" the faded area. 
##### My code

Here is my code that causes the problem.

```
<div class="navbar-fixed">
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Logo</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">Navbar Link</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav" style="left: 0px;">
        <li><a href="#">Navbar Link</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
</div>
```

I hope you guys will take a look at this soon because I think that the combination of `navbar-fixed` and the mobile slide out menu will be very common. 
Or perhaps am I just doing it wrong?

And again, sweet framework!

### PR DESCRIPTION
**Pull request by tomscholz**
resolve #1664, #3918, #4046, #4231, #437, #4318, #3982, #2879, #4187, #3844

### CODE REVIEW

**Comment by joshmorel** [comment]
Hi,

I also think you should add a note in the documentation on the option closeOnClick: true.

This is option enabled to true is the only thing that makes this workable for same-page anchors IMHO. JavaScript:

```
$(document).ready(function(){
    $(".button-collapse").sideNav({closeOnClick: true});
});
```

**Comment by acburst** [comment]
Is this necessary? most of the code is duplicated. Can we add a note instead about the placement of the side-nav?

**Comment by tomscholz** [comment]
@acburst Interesting question. I get the thing with the duplicate code, but most people don't even read the docs properly and just copy paste. I would be okay with a note, but if the issue still comes up, we could put the full code example in the docs. Ok?

**Comment by ScottBeeson** [comment]
In case anyone finds this before it is published, like I did, just move your second `ul` outside of the `.navbar-fixed` element.

**Pull request closed without merging**
