### PR TITLE
Deprecate bower in docs (#5586)

### PR DESCRIPTION
**Pull request by jacobq**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jacobq** [comment]
How about "not recommended" then? (since the bower website "recommends" using yarn/npm) Deprecated seems to imply that an end-of-support date is planned, but bower is still supported.

**Comment by jacobq** [comment]
@tomscholz would you like me to `/discouraged/deprecated/g` in this commit? If that will make it acceptable I will do so. (The precise wording is not particularly important to me.)

**Comment by nfgallimore** [comment]
A definition of deprecate is "express disapproval of"

**Comment by Dogfalo** [comment]
Thanks!

**Pull request merged**
