### PR TITLE
Display default inputs

### PR DESCRIPTION
**Pull request by developeranirudhprabhu**
Added pseudo classes  to the input selectors so that "browser-defaults" can be applied to other input fields (https://github.com/Dogfalo/materialize/issues/3975)

### CODE REVIEW

**Comment by developeranirudhprabhu** [comment]
@acburst @Dogfalo Can you kindly merge this PR?

**Comment by developeranirudhprabhu** [comment]
@acburst @Dogfalo Please merge the changes and do the needful soon

**Comment by developeranirudhprabhu** [comment]
@acburst @Dogfalo Please look into it and do the needful

**Comment by codescribblr** [comment]
+1 for getting this merged in. I needed this a month ago, so I'm running a mod in production.

**Comment by tomscholz** [comment]
@developeranirudhprabhu Why did you make changes to the `chips.js`?

**Comment by tomscholz** [comment]
@codescribblr How does your "mode" look like?

**Pull request closed without merging**
