### PR TITLE
Fix autoclose for timepicker

### PR DESCRIPTION
**Pull request by GermanBluefox**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Please describe your change a bit more.

**Comment by GermanBluefox** [comment]
I thought that my changes a visible in code. Anyway, if I activate autoClose option it does not work, because at this place the wrong object (pure DOM and not jQuery) will be used, that of course does not have any addClass method. DOM elements have only className.
I saw in this file, that jQuery is used and modified the object for jQuery.

If you do not want to use jQuery the code should be modified like this one

```
if (!this.minutesView.className || this.minutesView.className.indexOf('timepicker-dial-out') === -1) {
    this.minutesView.className += ' timepicker-dial-out';
}
setTimeout(function(){
        this.done();
}.bind(this), this.options.duration / 2);
```

**Comment by GermanBluefox** [comment]
You can fix the problem in this way too:

```
if (this.minutesView.className.indexOf('timepicker-dial-out') === -1) {
    this.minutesView.className += ' timepicker-dial-out';
}
setTimeout(() => {
        this.done();
}, this.options.duration / 2);
```

**Comment by Dogfalo** [comment]
I made a similar change here: cafc9724220ae48fdaab1d85e1f27a81a51a9859. Thanks for the help

**Pull request closed without merging**
