### PR TITLE
Datepicker: add support for closeOnSelect and closeOnClear options

### PR DESCRIPTION
**Pull request by benelliott**

### CODE REVIEW

**Comment by benelliott** [comment]
Hi @acburst, any chance of getting this merged in soon? Should be quite simple.

**Comment by DEKHTIARJonathan** [comment]
It would be wonderful to have a merge on this !

**Comment by MarianArlt** [comment]
Indeed this would be a wonderful feature to have. I think it's pretty standard UX and people appreciate not to have to make superfluous clicks.

**Comment by Dogfalo** [comment]
Merged in 40090b093f4b836258ad16dd98d32fe38f86aff0. 
I combined closeOnClear with closeOnSelect functionality

**Pull request closed without merging**
