### PR TITLE
Add Materialize Jasmine Testing Guideline Doc

### PR DESCRIPTION
**Pull request by ProfNandaa**
Transferred the documentation from the [shared Google
Doc](https://docs.google.com/document/d/1dVM6qGt_b_y9RRhr9X7oZfFydaJIEqB9CT7yekv-4XE/edit#)

### CODE REVIEW

**Comment by Dogfalo** [comment]
Hey @ProfNandaa. Can we add this as a section into CONTRIBUTING.md instead?

**Comment by ProfNandaa** [comment]
@Dogfalo - Sure, let me fix that right now.

**Comment by ProfNandaa** [comment]
@Dogfalo - done.

**Comment by Dogfalo** [comment]
Thanks!

**Pull request merged**
