### PR TITLE
Added url updates to scrollspy

### PR DESCRIPTION
**Pull request by klis87**
Url should be updated to be in sync with last clicked anchor to improve user experience. After page is reloaded, user will go back to the same point he was before.

### CODE REVIEW

**Comment by mitar** [comment]
I would love to see this in.

**Comment by J-tt** [comment]
@klis87 
If you could fix the conflicts that would be awesome!

**Comment by tomscholz** [comment]
I just tested this locally and it doesn't work

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.

**Pull request closed without merging**
