### PR TITLE
Add support for jQuery in noConflict mode

### PR DESCRIPTION
**Pull request by jmversteeg**
Materialize would break when used in an environment where jQuery was loaded in [`noConflict`](https://api.jquery.com/jquery.noconflict/) mode

### CODE REVIEW

**Comment by Baesch** [comment]
+1

**Comment by jmversteeg** [comment]
I did not include a `bin` version of the javascript assets but I could add one if required

**Comment by jmversteeg** [comment]
This one's pretty much a must when using Materialize.css in a WordPress environment -- please consider merging ASAP

**Comment by UriahsDev** [comment]
it says the pull requeest contains merge conflicts that must be resolved...not  sure what exactly that means (new gitter) but it might be stopping them.

**Comment by jmversteeg** [comment]
That's because I included a compiled version of the JS assets -- they should be able to just resolve using their version and then re-compile

**Comment by jmversteeg** [comment]
Merged changes from master back in -- should be automatically mergeable now

**Comment by Baesch** [comment]
+2

**Comment by acburst** [comment]
Sorry this slipped through the cracks. I just added it in a simple commit: 67c93cf

**Comment by acburst** [comment]
Thanks for letting us know.

**Pull request closed without merging**
