### PR TITLE
Add location of built file to package.json

### PR DESCRIPTION
**Pull request by NicholasAntonov**
Add a main property to package.json to allow importing of the built javascript when installed from npm

### CODE REVIEW

**Comment by jjalonso** [comment]
This should be merged. webpack is trending now...

**Comment by zachrip** [comment]
+1

**Comment by kennyledet** [comment]
+1

**Comment by sylvaiam** [comment]
+1

**Comment by Agowan** [comment]
+1

**Comment by jjalonso** [comment]
Why this pull request is ignored since 3 month ago?

**Comment by tinybug** [comment]
+1

**Comment by lbialy** [comment]
+1

**Comment by ProfNandaa** [comment]
@NicholasAntonov - please fix the merge conflicts.

**Comment by NicholasAntonov** [comment]
This was manually resolved in the master branch.

**Pull request closed without merging**
